### ISSUE TITLE
Signing-out throws 'Warning: Can't call setState(or forceUpdate) on...'

### ISSUE THREAD

**Issue by amant** [aws-amplify/amplify-js#1012]
New to aws-amplify-react-native library. When I sign-out I get this warning. 

```
Warning: Can't call setState (or forceUpdate) on an unmounted component. 
This is a no-op, but it indicates a memory leak in your application. 
To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method. in Authenticator (created by Wrapper)
```

![android emulator - nexus_5x_api_25_5554](https://user-images.githubusercontent.com/661338/41278552-61782e0c-6e2a-11e8-8f0a-014f05c80bca.png)

Here is a simple code that I used. Am I doing something wrong? 

```
import React from 'react';
import { Text, View } from 'react-native';
import Amplify from 'aws-amplify';
import awsConfig from './src/aws-exports';
import { withAuthenticator } from 'aws-amplify-react-native';

Amplify.configure(awsConfig);

class App extends React.Component {
  render() {
    return (
      <View><Text>Hello world</Text></View>
    );
  }
}

export default withAuthenticator(App, { includeGreetings: true });
```

**Comment by phoenecke** [comment]
Adding:
```
  componentDidMount() {
    this.mounted = true
  }

  componentWillUnmount() {
    this.mounted = false
  }
```
to Authenticator.js and guarding the `setState` call fixes it.. but I don't know if that is the right fix...

**Comment by amant** [comment]
If I use <Authenticator /> component directly and signout, I don't get this warning. For me then, it seems like issue is with how the withAuthenticator() is implemented. 

I have been trying to follow the callstack, and for life of me I can't understand why Authenticator.js's checkUser() method in this part Auth.currentAuthenticatedUser()....catch(...) triggers this warning.

**Comment by merunga** [comment]
hi @amant did you find a workaround for this, still using `withAuthenticator`?

**Comment by merunga** [comment]
Hi @amant sorry for the late reply. I solved my issue and it was not related to amplify!

My problem was that there was an animation set with `setInterval` in my custom `Loading` screen. All I had to do was exactly what the warning message was telling me: trigger a `clearInterval` in `componentWillUnmount`.

According to your snippet, you are not using custom screens, but my recommendation: check the exact line in the warning message where `AuthPiece` is being called, it points to the custom screen that has the problem (I was a little confused because it was telling me that the problem was with `AuthPiece` and not any of my screens, but all my screens inherit from their default counterparts that inherit from `AuthPiece` themselves).

```jsx
export default withAuthenticator(ConnectedApp, false, [
  <Loading />, // <-- this what the problematic line according to the warning... and was indeed true!!!
  <SignIn />,
  <ConfirmSignIn />,
  <SignUp />,
  <ConfirmSignUp />,
  <ForgotPassword />,
]);
```

Hope it can help you

**Comment by merunga** [comment]
@amant finally managed to get rid of this warning!
The origin of the problem is [here](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react-native/src/Auth/Authenticator.js#L75). The Promise gets triggered but is not resolved before the component is unmounted.
My solution? I used [`promise-cancel`](https://www.npmjs.com/package/promise-cancel) and a custom `Authenticator`.
```js
export default class Authenticator extends React.Component {
  // ...
  componentWillMount() {
    this.checkUser(); // <-- problematic line
  }

  componentWillUnmount() {
    this.checkingUser.cancel();
    this.checkingUser.abort();
  }
  
  // ...

  checkUser() {
    const { authState } = this.state;
    const statesJumpToSignIn = ['signedIn', 'signedOut', 'loading'];
   // use promise-cancel
    this.checkingUser = promiseCancel(Auth.currentAuthenticatedUser())
    this.checkingUser.promise.then((user) => {
      if (user) {
        this.handleStateChange('signedIn', null);
      } else if (statesJumpToSignIn.includes(authState)) {
        this.handleStateChange(startScreen, null);
      }
    })
    .catch((err) => {
      if (statesJumpToSignIn.includes(authState)) {
        this.handleStateChange(startScreen, null);
      }
      logger.debug(err);
    });
  }

  // ...
}
```

I don't know if this is an acceptable solution, but it worked. Glad to create a PR if appreciated.

Hope this helps

**Comment by amant** [comment]
@merunga Seems like good solution to me, I will use your solution. Thanx a lot! 
I miss ability to cancel in the native promise.

**Comment by merunga** [comment]
Let me know if it works for you

**Comment by michaelcuneo** [comment]
This is still an issue in aws-amplify-react ... I use a hub listener to detect signIn and signOut to run my signIn and signOut dispatching... from the Authentication Manager with the Hub listener I dispatche all of my login logic to determine usernames, settings, etc... then I change the location from the result of this...  to the signed in areas. But still, after all of this, the Authenticators own listener finally decides to trigger signedIn, but the component has well and truly been unmounted by this stage.

This is 100% what is occurring in the react native and react js apps. People leave and navigate away from the login after login has successfully occurred, but the hub is still performing tasks while the Authenticator has been unmounted. Is there some kind of way to sync the 'signIn, and / or signedIn' components of the Hub, instead of providing SignedIn for the Authenticator Hub component and the external Hub component. Why are they even a different thing? Can't they just be the same?

If I listen to signedIn, ... it never happens because you can't listen to signedIn from the Hub.listener... but it somehow does trigger, but it's way too late.

We need to somehow allow the Hub to listen for the signedIn state... not signIn... we don't care if we're about to signIn, because at this stage, anything could be anywhere.

This also related to my issue that <Greetings> doesn't show anything anymore... if I sign in with my old method which was horrific, where containers were not seperate, and they were all running dependant on each other, it worked fine, but it was horrible code.

I wish this would just plain work.

**Comment by powerful23** [comment]
@michaelcuneo thanks for your feedback! We have a plan to refactor the Hub module recently and will try the best to solve the issues you mentioned.

**Comment by amirmishani** [comment]
Having the same issue as @michaelcuneo with the hub listener. Looking forward to it being resolved soon.

**Comment by amirmishani** [comment]
@michaelcuneo I was having the same issue with the hub listener. But it seems like the Authenticator is  fixed in the latest update to aws-amplify-react.

**Comment by michaelcuneo** [comment]
Hmm. I still have the issue with the latest. I’ll double check when I’m back in the office.

**Comment by michaelcuneo** [comment]
@amirmishani ... and thankfully, the latest stable also fixes the issue i had with Greetings being invisible and rendering null. My project is now 100% repaired.

@powerful23 works great now. Thanks for the codes. 👍

**Comment by ElektrikSpark** [comment]
I am still getting this warning when signing out after navigating to another page using aws-amplify-react:

> Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method. in class_1 (at signin.js:5) in div (at signin.js:4) in SignInPage (at _app.js:33)

Is this still a known issue for aws-amplify-react or is my implementation wrong by chance?
