### ISSUE TITLE
import Amplify fails on Expo apps 

### ISSUE THREAD

**Issue by tannerabread** [aws-amplify/amplify-js#11247]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Not applicable

### Amplify Categories

Not applicable

### Environment information

<details>

```
# Put output below this line

 System:
    OS: macOS 13.3
    CPU: (8) arm64 Apple M1
    Memory: 89.64 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/Library/Caches/fnm_multishells/82729_1681314124674/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - ~/Library/Caches/fnm_multishells/82729_1681314124674/bin/npm
    Watchman: 2023.04.10.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 112.0.5615.49
    Firefox: 102.9.0
    Safari: 16.4
  npmPackages:
    @babel/core: ^7.20.0 => 7.21.4 
    @react-native-async-storage/async-storage: ^1.18.1 => 1.18.1 
    @react-native-community/netinfo: ^9.3.9 => 9.3.9 
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: ^6.2.0 => 6.2.0 
    aws-amplify: ^5.1.1 => 5.1.1 
    core-js: ^3.30.1 => 3.30.1 
    expo: ~48.0.11 => 48.0.11 
    expo-status-bar: ~1.4.4 => 1.4.4 
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
  npmGlobalPackages:
    @aws-amplify/cli: 10.7.3
    @ionic/cli: 7.0.1
    corepack: 0.14.1
    create-expo-app: 1.3.2
    eas-cli: 3.5.2
    expo-cli: 6.1.0
    ios-deploy: 1.12.1
    npm: 9.5.1
    tree-cli: 0.6.7
    verdaccio-memory: 10.3.0
    verdaccio: 5.20.1

```

</details>

### Describe the bug

Expo app is throwing the error 
```console
Unable to resolve "@aws-amplify/rtn-push-notification" from "node_modules@aws-amplify\notifications\lib-esm\PushNotification\PushNotification.native.js"
```
when trying to install/import Amplify package

### Expected behavior

Expo app is able to import Amplify without the build complaining about `@aws-amplify/rtn-push-notification` when not trying to use the category

### Reproduction steps

1. npx create-expo-app amplified_todo
2. npm install aws-amplify amazon-cognito-identity-js @react-native-community/netinfo @react-native-async-storage/async-storage core-js
3. added import { Amplify } from 'aws-amplify'; to my app.js
4. npm run android
5. Get the following error:
Unable to resolve "@aws-amplify/rtn-push-notification" from "node_modules@aws-amplify\notifications\lib-esm\PushNotification\PushNotification.native.js"

### Code Snippet

```javascript
// Put your code below this line.
import { Amplify } from 'aws-amplify';
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Mobile Device

Android Emulator

### Mobile Operating System

SDK 31

**Comment by tannerabread** [comment]
Also fixed by updating `babel.config.js` to:
```js
module.exports = function (api) {
  api.cache(true);
  return {
    presets: [
      [
        "babel-preset-expo",
        {
          lazyImports: true,
        },
      ],
    ],
  };
};
```

**Comment by tannerabread** [comment]
Fixed in amplify v5.1.2

**Comment by jgo80** [comment]
> Fixed in amplify v5.1.2

Sorry, this is not true. When importing `import { DataStore } from 'aws-amplify';` I still receive `Error: Unable to resolve module ./node_modules/@aws-sdk/client-pinpoint/dist-cjs/models/PinpointServiceException` with `"aws-amplify": "^5.1.2"`.

**Comment by tannerabread** [comment]
@jgo80 can you give more details of your project? I am not seeing this error on either iOS or android emulators

Full package.json:
```json
{
  "name": "hosted-slow",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.18.1",
    "@react-native-community/netinfo": "^9.3.9",
    "aws-amplify": "^5.1.2",
    "expo": "~48.0.11",
    "expo-status-bar": "~1.4.4",
    "react": "18.2.0",
    "react-native": "0.71.6"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}

```

App.js:
```js
import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';

import { DataStore } from 'aws-amplify';

export default function App() {

  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

```

**Comment by jgo80** [comment]
I spotted the difference. It will work in a regular repo, but **it will not work in a mono repo**.

Beside just importing `DataStore` you also should call a class function to invoke it, e.g.:
```ts
  useEffect(()=>{
    DataStore.query(User).then(console.log)
  },[])
```

**Comment by jgo80** [comment]
I could identify and resolve the problem. If anybody (hello future me) should experience this problem within a [mono repo setup with the official Expo Docs](https://docs.expo.dev/guides/monorepos/), you may change your `metro.config.js` as follows:

```js
const { getDefaultConfig } = require('expo/metro-config');
const blacklist = require('metro-config/src/defaults/exclusionList');
const path = require('path');

// Find the project and workspace directories
const projectRoot = __dirname;
const workspaceRoot = path.resolve(projectRoot, '../..');
const config = getDefaultConfig(projectRoot);

// Watch all files within the monorepo
config.watchFolders = [workspaceRoot];

// Exclude Amplify Backend
config.resolver.blacklistRE = blacklist([
  /amplify\/#current-cloud-backend\/.*/,
]);

module.exports = config;
```

**Comment by tannerabread** [comment]
Thank you for leaving this here for others to find @jgo80 !
And glad you unblocked yourself

**Comment by tlmader** [comment]
@jpo80 Also using Expo + Amplify + Yarn Workspaces over here, and I've been stuck on Expo SDK 45 until I read your solution tonight lol! This should be included in the Expo docs. Thank you so much!!!

**Comment by markedwards** [comment]
In my case I only had to remove `config.resolver.disableHierarchicalLookup = true;`

@jgo80 can you speak to the potential downside of doing this?  Perhaps an issue should be opened in Expo.
