### ISSUE TITLE
[React][aws-amplify-react] - Page reload briefly shows authentication screen

### ISSUE THREAD

**Issue by Legym** [aws-amplify/amplify-js#1332]
I am using `withAuthenticator` as a HOC to add authentication to my React app. My issue is that if you are logged in and you refresh the app, it will flicker and briefly show the login screen before rendering the component. I have tried `<Authenticator />` and also have gotten the same issue.

It is the same issue as #233 

I used this example.
https://aws-amplify.github.io/amplify-js/media/authentication_guide.html#using-withauthenticator-hoc

**Comment by yalamber** [comment]
Same issue for me as well. I also have issue #1334, greetings are not updated after signin. Do you also experience issue with greetings?

**Comment by harshayburadkar** [comment]
I am now facing the same issue. It makes the experience looks bad and I am afraid we would have to end up not using the UI provided by Amplify if this doesn't get fixed. 

These features should be marked Beta in the documentation until the UI/UX provided by Amplify is of the standard that AWS deserves to be at. I am was considering Amplify for a serious project but some issues make me want to reconsider. Kindly take note of this and either fix the critical issues or add a beta flag to features everywhere in the documentation which aren't up to the mark yet.

**Comment by powerful23** [comment]
@Legym Thanks for your feedback. I've added it as a story in our icebox.

**Comment by Legym** [comment]
I upgraded my npm package aws-amplify-react to the latest version and this issue has been fixed. Really like the new design as well. Thank you!

**Comment by yalamber** [comment]
for me even upgrading to latest version did not fix the issue.

**Comment by yalamber** [comment]
I am using the latest version but using Authenticator component instead of withAuthenticator HOC. I will check with withAuthenticator HOC as well. 

```
<Authenticator hideDefault={true} theme={MyAmplifyTheme} onStateChange={this.handleAuthStateChange}>
          <AppContainer />
          <SignIn />
</Authenticator>
```

**Comment by yalamber** [comment]
ok seems like ncu did not update the packages properly. With latest version. it seems to be working great. nice designs as well. great work.

**Comment by powerful23** [comment]
@yalamber hideDefault is used to hide those default auth components so you can put your customized ones. I am not fully understanding your question. You mean you the `AppContainer` doesn't show up when signed in if `hideDefault` is true?

**Comment by flyingace** [comment]
Hi. I am experiencing this issue using aws-amplify-react v2.1.4. I am using the `withAuthenticator` HOC. After authenticating, while the auth token is still valid if I refresh the page I see the sign-in page for a brief second before I am taken to the app.
I could try adding a conditional to the beginning of my LoginPage component's render method that checks whether the authState is 'SignIn' and only render if this is the case but it seems that this goes against the general intention of how Auth is meant to work.
