### ISSUE TITLE
Unable to verify secret hash for client

### ISSUE THREAD

**Issue by PedroS11** [aws-amplify/amplify-js#1368]
When signing in or signing up with aws amplify for js, it gives that error. The user pool has client secret checked and I need it like that. Is there any solution for this problem or is still a feature to be implemented?

**Comment by PedroS11** [comment]
I managed to get the sign up working based on a workaround found in stack overflow, however, the authenticateUser continues to give the same error


Here is my code

**Comment by maksimsemenov** [comment]
I'm getting the same issue, when using `Auth`class and trying to sign up a user:
```
Auth.signUp(email, password)
```

My Auth config:
```
Auth.configure({
  identityPoolId: process.env.AWS_IDENTITY_POOL_ID,
  mandatorySignIn: true,
  region: process.env.AWS_REGION,
  userPoolId: process.env.AWS_USER_POOL_ID,
  userPoolWebClientId: process.env.AWS_USER_POOL_CLIENT_ID,
  authenticationFlowType: 'USER_SRP_AUTH'
})
```

I looked at the sources for `Auth.signUp` and down the line, but couldn't find any code that generates `secretHash` and signs the request.

Is there any workaround? Is anyone working on this issue?

**Comment by ngocketit** [comment]
Got the same error. It looks like Amplify currently doesn't support client with secret. Could someone please confirm?

**Comment by jordanranz** [comment]
@ngocketit, client secret is currently not supported, correct. I'll mark this as a feature request.

**Comment by billynorris** [comment]
Any eta?

**Comment by pulpfree** [comment]
Also looking for an update on this.

**Comment by gpowerone** [comment]
I'll add myself to the list of people looking for an update on this

**Comment by C-Kenny** [comment]
+1

**Comment by jeremysquires-sensorup** [comment]
+1 as well

**Comment by JCole45** [comment]
1+

**Comment by YeonwooSung** [comment]
+1 as well

**Comment by ilgityildirim** [comment]
+1

**Comment by FadiAboMsalam** [comment]
same here

**Comment by dmitrysidorenko** [comment]
+1

**Comment by rutum** [comment]
+1 (or +233323232323 - if that can speed up the process to support this)

**Comment by singha53** [comment]
+1 although it works with amplify auth add (with client secret)

**Comment by janoist1** [comment]
+1 🤷‍♂️

**Comment by hendiche** [comment]
+1
Still no support for client secret, (except the uncheck way that sir @FadiAboMsalam mention above)

**Comment by hector16** [comment]
+1

**Comment by alex-cory** [comment]
+1...

**Comment by m1m6** [comment]
+1....

**Comment by hnajera** [comment]
+1

**Comment by ajdinahmetovic** [comment]
+1

**Comment by shaktiks** [comment]
any update on this yet?

**Comment by ericclemmons** [comment]
Hi everyone,

**Because this is an important & popular issue to the community**, I wanted to update everyone that we're continuing to investigate this.  Here are our next steps:

1. Engage our internal teams to validate our findings & security implications of #4490.
1. Based on that direction, determine what documentation, client, & server-side changes are necessary.

We did meet with the Cognito service team and learned a bit more about client secrets:

- The client secret is primarily for server-to-server communication: if it's bundled in the client, then anyone can access unintended resources unintentionally.

  (This isn't specific to Cognito, as others like [Auth0 has a dedicated page on this topic](https://auth0.com/docs/applications/concepts/client-secret))

  Since Amplify JS is intended for client-side usage, this raises security concerns that can have an unintentional impact.

- [Cognito's docs](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-client-apps.html) mention something similar:

  > It is your responsibility to secure any app client IDs or secrets so that only authorized client apps can call these unauthenticated APIs. 
  > ...
  > If a secret is created for the app, the secret must be provided to use the app. Browser-based applications written in JavaScript may not need an app with a secret. 

- `amplify add auth` is the preferred way of creating pools, and solves for many of these issues.

For those with this issue, has unchecking this box resolved the issue?
> <img width="631" alt="Screen Shot 2019-12-06 at 3 49 40 PM" src="https://user-images.githubusercontent.com/15182/70364121-12c38b00-1840-11ea-84ca-ada95cb666f9.png">

Or is there a use-case that you can provide more information on why this doesn't fit your needs?

Thanks, and please keep the feedback coming!

**Comment by ericclemmons** [comment]
We'd like to understand more what situations _don't_ allow for unchecking the _Generate client secret_ box:

> ![generate client secret](https://user-images.githubusercontent.com/15182/70364121-12c38b00-1840-11ea-84ca-ada95cb666f9.png)

Can you share what scenarios require the client secret so that we can better accommodate them?

Thanks!

**Comment by alimuhammad01** [comment]
+1

**Comment by ilgityildirim** [comment]
actually there is no sense for further discussion. By definition secret shouldn't be exposed. This is intended behavior after all.

**Comment by ericclemmons** [comment]
We're still looking to learn more about circumstances that aren't resolved by unchecking the "Generate client secret" button:
> https://github.com/aws-amplify/amplify-js/issues/1368#issuecomment-564311714

**Comment by ronkorving** [comment]
This is still an issue when for development purposes on a client app that in normal situations should use a secret, where one wants to create a dev-user from a local environment in that pool.

**Comment by ericclemmons** [comment]
@ronkorving Thanks for the response.  I don't fully understand your example, can you provide more details?

> ...in normal situations should use a secret

For those situations, is "Generate client secret" checked/unchecked?
> https://github.com/aws-amplify/amplify-js/issues/1368#issuecomment-564311714

**Comment by ronkorving** [comment]
I'm doing local development, with a user pool on my development account.
Generate client secret is checked, because that's my normal flow. I want to be able to create test users quickly though, not having to go through any confirmation process. The user is just for development, but I do want the user pool client's auth flow to be identical to production.

What I did now as a workaround was to create a script that creates a temporary client on my pool that does not have a secret, then create my test-user, then remove that temporary client. It solves the problem.

**Comment by scionwest** [comment]
I too see a need for this. In my case I have an API Gateway fronting a NodeJS Lambda. My API acts as a proxy for Cognito - abstracting it away so clients only interact with my API surface area.

Because of this, my Lambda handles the signUp and auth calls to Cognito on behalf of the user. The client devices POST their credentials to my API and I forward them along to Cognito. In this use-case a ClientSecret would be desirable between my Lambda and Cognito and not just a ClientId.

**Comment by scionwest** [comment]
I suppose I should clarify... My use-case is the aws-sdk and not Amplify-js... I 100% agree Amplify itself should not support this as client-side deployments should not include secrets. Secrets are typically used for server to server authorization. I believe aws-sdk provides this when I look [at the docs]( https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#signUp-property).

**Comment by castledraw** [comment]
Hi @ericclemmons , I want to login my amplify app with a cognito appclient with secret key. There is required for me, because i configured an elasticsearch instances with cognito, and automatically thats created an appclient with secretkey. So i want to load a dashboard kibana in my amplify app, but i received de same error Unable to verify secret hash for client.

I can't create another appclient without secret key, because elasticsearch use another with this.

**Comment by cuni0716** [comment]
I just write a workaround that worked for me:

```typescript
    import * as fetchIntercept from "fetch-intercept";

    fetchIntercept.register({
      request: (url, config) => {
        if (config && config.headers && !!config.headers["X-Amz-Target"]) {
          const body = JSON.parse(config.body);
          let username: string;

          if (config.headers["X-Amz-Target"] === "AWSCognitoIdentityProviderService.InitiateAuth") {
            username = body.AuthParameters.USERNAME;
            body.AuthParameters.SECRET_HASH = this.hashSecret(username);
          } else if (config.headers["X-Amz-Target"] === "AWSCognitoIdentityProviderService.RespondToAuthChallenge") {
            username = body.ChallengeResponses.USERNAME;
            body.ChallengeResponses.SECRET_HASH = this.hashSecret(username);
          } else {
            username = body.Username;
            body.SecretHash = this.hashSecret(username);
          }

          config.body = JSON.stringify(body);
        }

        return [url, config];
      },
    });
```

I hope that could be usefull for someone!

**Comment by nukeop** [comment]
I'm getting this error when using the signUp function, even without a client secret for my user pool. I'll check the above workaround.

**Comment by diprajkuwar** [comment]
Since the customization of the Cognito Hosted UI is not possible, I am developing the same sort of UI/Authentication mechanism using Amplify / React, but the Sign In fails for Client with Secret.  If I use client without secret the Sign In process works but TOKEN endpoint oauth2/token fails as it requires the client secret.

**Comment by nukeop** [comment]
We developed a mechanism where the backend exposes an endpoint that lets the frontend generate hashes for usernames, then we inject them into requests by using the method described by @cuni0716 above. This way the client secret stays hidden from clients but we're still able to sign requests.

**Comment by NoahGrayDL** [comment]
I tried to connect my existing cognito userpool by Amplify 'withAuthenticator' and it returns this error. The Cognito user pool already has its client secret. If there are no ways to add hash key on this 'withAuthenticator', do I need to develop all the parts...? 😥
