### ISSUE TITLE
Greetings and SignOut components gone.

### ISSUE THREAD

**Issue by michaelcuneo** [aws-amplify/amplify-js#2329]
Since about AA, 1.1.10 and AAR 2.1.0 respectively... <Greetings /> and <SignOut /> are both seemingly not renderable in any of my projects.

I am successfully logged in as a Cognito User but It renders nothing. No errors, no warnings, just nothing.

**Comment by haverchuck** [comment]
@michaelcuneo - Can you post the exact versions you have from your package.json?

**Comment by michaelcuneo** [comment]
This hasn't worked since a version quite a long while back... but my current version is ...

    "aws-amplify": "^1.1.14",
    "aws-amplify-react": "^2.2.1",

**Comment by haverchuck** [comment]
@michaelcuneo - Are you using the react HOC or putting component tags in your jsx directly?  Can you post how you are including the authenticator?  I'll try to reproduce.

**Comment by michaelcuneo** [comment]
The tags are being placed into the JSX Directly, as components.

**Comment by haverchuck** [comment]
@michaelcuneo Can you please post how you are using the Greetings component?

**Comment by michaelcuneo** [comment]
import { Greetings } from ‘aws-amplify-react’

... 

<Greetings />

...

**Comment by haverchuck** [comment]
@michaelcuneo -  Try this:  
```
            <Greetings  
                        authState={this.authState} // -> should be 'signedIn' for component to display
                        authData={this.authData} // -> your CognitoUser
             />
```
Does that help?

**Comment by michaelcuneo** [comment]
I've added this kind of setup, but it did not fix the issue.

Authenticator is in a container called LoginPage... which loads up when login is needed... 

Greetings, or SignOut (Both fail to work) is in a component called UserWidget, loaded up by my Header Container, when applicable.

My main App is wrapped by an AuthManager provider, which is the Auth Hub listener, which changes loggedIn State and grabs user information for the apps purposes.

So Authenticator, and Greetings are in entirely seperate areas of the app. Adding
const thisAuthState = true;
<Greetings authState={thisAuthState} /> to ensure that authState is true, also does not make it render.

**Comment by haverchuck** [comment]
@michaelcuneo Are you passing the CognitoUser to SignOut?

**Comment by michaelcuneo** [comment]
I’ve never had to before. Why would I be doing it now?

**Comment by haverchuck** [comment]
@michaelcuneo  I'm digging into this.

**Comment by haverchuck** [comment]
@michaelcuneo I have merged a fix for this into our master branch.  It should be available on our unstable tag shortly (npm i aws-amplify-react@unstable).

**Comment by michaelcuneo** [comment]
Even after merging this into my app, it still doesn't display any Greetings component. My Greetings component renders no content at all. It's as if the entire system doesn't actually manage my authentication states anymore, even though it used to, and I'm not using it any different than I used to... I'm trying all manner of workarounds and patches to fix it, but I don't think this is the best solution for something that is meant to be a HOC.

**Comment by michaelcuneo** [comment]
I finally got the components back, after updating to the latest version of the HOC's, but now the SignOut doesn't exist, (No idea why, it's still in the documentation), and Greeting component is no longer using my theme={CustomTheme} ... has theming been removed from the Greetings HOC?

**Comment by jordanranz** [comment]
I'll go ahead and reopen this issue so we can investigate.

**Comment by jordanranz** [comment]
Hey @michaelcuneo,

I am able to see the Greetings component with the SignOut component inside of it and a custom theme applied to it. Can you post how you are using the HOC and what your CustomTheme object looks like?

**Comment by michaelcuneo** [comment]
I am using it the way it was intended I assume... the authenticator and signout/greetings HOC have always meant to be seperate? No one ever assumes to have a login screen with a massive sign out component in it's place... it's not UX/UI logical.

I have my entire project set out like this... I run an AuthManager which is a provider. It wraps <App />

```
          <AuthManager>
            <App />
          </AuthManager>
```

AuthManager is a single provider container that initiates a Hub.listen.

The Hub Listen dispatches auth login and auth logout events to a saga which sets and removes all of the my apps user state, active state, history, etc... 

My login page, is a single route, that just presents

`<Authenticator key="Authenticator" hide={[Greetings]} theme={rprTheme} />,`

My Greetings and/or SignOut component, (Which last I read were two entirely different things, no idea why we have two?) is in my headers as a widget. Which is responsive and acts variable depending on the size of the screen... can be on the side in a burger-menu for mobile, or on the top of the screen within a modal drop down (similar to FB's)

Either way that I render the Greetings or SignOut Components, it doesn't take the theme, or any other settings that I apply that are actually valid props for Greetings or SignOut. It appears to completely ignore those props, and draws... 

Hello Michael Cuneo
with a massive orange SIGN OUT.

**Comment by michaelcuneo** [comment]
I would have just used the Authenticator alone and triggered directly from it, for my login/logout, but the Authenticator HOC doesn't trigger it's onSignIn action in a way that synchronises with the actual response from it's own service... so by the time you look at the results from onSignIn, they're actually null... but... if you use the Hub.Listen, this method is actually filled with data by the time it gets this far... so this was my organised response to a bug that was never fixed. 👍

All of this detail should probably be in another thread here on GitHub, but I can't explain how I use the Greetings and SIgnOut component in any other way than this... 

So, I tried theming again today, and it works fine... but I did have to make one change to make it work.

` export default rprTheme;`

to 

` export default AmplifyTheme;`

It appears as though, the AmplifyTheme doesn't like to be renamed, even when you're using it the same way any other component should work, I renamed it back to AmplifyTheme through the entire project, and now it's theming.

**Comment by michaelcuneo** [comment]
Sorry, had to update again, I was wrong, the Greetings / SignOut component is still receiving no theme from my custom theme. I can customise the Authenticator component, but not Greetings or SignOut.

**Comment by michaelcuneo** [comment]
I cannot remember how but I solved this quite some time ago... if I recall exactly what the issue was, I'll add the appropriate fix.

**Comment by tasmiaorni** [comment]
hello  whenever i am using this : <amplify-authenticator hide={[Greetings]}></amplify-authenticator> in my auth.component.html  , both the user name  and signout option is gone. I want to keep the signout option.How can I do that??

**Comment by tasmiaorni** [comment]
hello whenever i am using this :**<amplify-authenticator hide={[Greetings]}></amplify-authenticator>** in my auth.component.html , both the user name and signout option is gone. I want to keep the signout option.How can I do that??

**Comment by tasmiaorni** [comment]
using this 
![image](https://user-images.githubusercontent.com/31642602/69761559-ba043c00-1135-11ea-9b7f-c29277469d33.png)

in auth.component.html removes both the freetings and signout . How can I keep the signout??

**Comment by michaelcuneo** [comment]
> using this
> ![image](https://user-images.githubusercontent.com/31642602/69761559-ba043c00-1135-11ea-9b7f-c29277469d33.png)
> 
> in auth.component.html removes both the greetings and signout . How can I keep the signout??

You cannot remove [Greetings] and still have the SignOut, unless you customise the Greetings so that it doesn't say anything, yet still contains the button... alternatively reconstruct your own signOut ... if you build a Hub listener that will perform whatever actions your own App needs after signOut, all you need to do is make a button that calls 'Auth.signOut() on click... and the Hub will take care of the rest. 

I have an AuthProvider, which is just the Authentication Hub wrapping my entire app, that way I can seperate the login/logout and have them in entirely different areas of the single page app. The hub just listens and performs state management accordingly.
