### ISSUE TITLE
Could not find a declaration file for module '@aws-amplify/ui'

### ISSUE THREAD

**Issue by samuelcastro** [aws-amplify/amplify-js#2460]
**Describe the bug**
When trying to build a typescript project I'm getting: **Could not find a declaration file for module '@aws-amplify/ui'**:

```
node_modules/aws-amplify/lib/index.d.ts:8:16 - error TS7016: Could not find a declaration file for module '@aws-amplify/ui'. '/Users/samuelcastro/Projects/Control4/react-sdk/node_modules/@aws-amplify/ui/dist/aws-amplify-ui.js' implicitly has an 'any' type.
  Try `npm install @types/aws-amplify__ui` if it exists or add a new declaration (.d.ts) file containing `declare module '@aws-amplify/ui';`

8 import UI from '@aws-amplify/ui';
```

**To Reproduce**

1. In a typescript (3.1.2) project run: `./node_modules/.bin/tsc`

**Expected behavior**
Successfully build

**Comment by jordanranz** [comment]
Hey @samuelcastro, how are you including amplify into your project?

**Comment by samuelcastro** [comment]
Yeah, an easy workaround would be just include it, I just wanted to see if a better solution is being take, like a define typescript definition of it.

Thanks anyway.

**Comment by ffxsam** [comment]
Just stumbled upon this too. Everything else has a proper type declaration file in `@aws-amplify`. So this seems like just a tiny oversight. Other folders such as `@aws-amplify/cache` have a `lib` folder full of `.d.ts` files. But the UI folder does not.

**Comment by pl4yradam** [comment]
This should not be marked as a feature request, it completely breaks compiling

**Comment by vuongnguyen-agilityio** [comment]
Add `"@aws-amplify/ui": "1.0.18",` to package.json, below `"aws-amplify": "1.1.26",` and good luck :))

**Comment by willkara** [comment]
Any updates on this for Angular 8 support?

**Comment by rjjlucy** [comment]
I added 
`    "noImplicitAny": false,`
in my tsconfig.json and seems like the error is gone.

**Comment by sammartinez** [comment]
As the above callouts and merged PRs, this is resolved. Closing this issue

**Comment by half2me** [comment]
@sammartinez I still have this issue on the latest version. How do I solve it?

**Comment by kevin4dhd** [comment]
same problem

**Comment by rekomerio** [comment]
Problem is here also. I'm trying to just use `withAuthenticator` in React and it crashes everything

**Comment by RobinBeekhof** [comment]
I have this problem to with the latest version
