### ISSUE TITLE
[aws-amplify-react] ChatBox has render ChatBotInputs component with repeated micText

### ISSUE THREAD

**Issue by mags749** [aws-amplify/amplify-js#2574]
**Duplicate micText while rendering ChatBotInputs**
ChatBox render method has ChatBotInputs component which has repeated property at line no 320 and 330.
https://github.com/aws-amplify/amplify-js/blob/99092bc51986b28f63c8fce48bdf722354c96516/packages/aws-amplify-react/src/Interactions/ChatBot.jsx#L320

https://github.com/aws-amplify/amplify-js/blob/99092bc51986b28f63c8fce48bdf722354c96516/packages/aws-amplify-react/src/Interactions/ChatBot.jsx#L330

This code generates a minified version (in dist) with following code:
`React.createElement(ChatBotInputs, { micText: this.state.micText, voiceEnabled: this.props.voiceEnabled, textEnabled: this.props.textEnabled, styles: styles, onChange: this.changeInputText, inputText: this.state.inputText, onSubmit: this.submit, inputDisabled: this.state.inputDisabled, micButtonDisabled: this.state.micButtonDisabled, handleMicButton: this.micButtonHandler, micText: this.state.micText, currentVoiceState: this.state.currentVoiceState }))));`

This would add micText twice to the generated files. This code breaks in IE with following error in browser:
`Multiple definitions of a property not allowed in strict mode`.

For now I have reverted by aws-amplify-react to 2.1.4. But due to this, application using the latest aws-amplify-react breaks on IE (Although it works on other browsers).

This issue description has the solution as well. :smiley:

**Comment by haverchuck** [comment]
@mags749  - We merged a fix for this into our @unstable build (will take a while to propogate).  Should be availabe in main build in coming days. Thanks!

**Comment by jukkahuuskonen** [comment]
Anyone else still having this same problem? I'm on v.2.3.2 and IE11 gives the same 
'Multiple definitions not alloweed in strict mode' error.
