### ISSUE TITLE
Auth.federatedSignIn error: `AuthClass - Cannot get the current user because the user pool is missing.`

### ISSUE THREAD

**Issue by bharat-tiwari** [aws-amplify/amplify-js#2603]
**Describe the bug**
`Auth.federatedSignIn` throws a console error `AuthClass - Cannot get the current user because the user pool is missing.`, but works as expected finally by authenticating successfully after that.

I have AWS Identity pool configured with OpenID Connection as Auth provider to authenticate for multiple Google ClientIds. I am not using any cognito user-pool.
From my react-native app, using Amplify SDK, I call `Auth.federatedSignIn` passing it the idToken obtained from Google SignIn. Everything is working good, AWS finally authenticates successfully and allows to access lambdas. 

**Expected behavior**
`Auth.federatedSignIn` should authenticate without throwing any console error

**Screenshots**
( the error is highlighted in console in below gif )

![gfgh](https://user-images.githubusercontent.com/13016554/51700184-1e191980-1fd4-11e9-8aaa-aa10951fadc2.gif)

Below is how I have Amplify Auth configured:
![gfgh2](https://user-images.githubusercontent.com/13016554/51697768-3e45da00-1fce-11e9-9c4c-6b34833894bc.png)

**Smartphone (please complete the following information):**
 - Device: [iPhone Simulator, Android Simulator ]
 - OS: [ iPhone X simulator 12.1, Android Nexus 5x API28]

**Additional context**
    "aws-amplify": "^1.1.19",
    "aws-amplify-react-native": "^2.1.7"

Tried removing/adding above packages to have latest versions.

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by vkulov** [comment]
We are getting the same thing.
`AuthClass - Cannot get the current user because the user pool is missing. Please make sure the Auth module is configured with a valid Cognito User Pool ID`

This page suggests that user pool id is optional.
https://aws-amplify.github.io/docs/js/authentication#manual-setup

On the other hand this code suggests that it's not optional:
https://github.com/aws-amplify/amplify-js/blob/master/packages/auth/src/types/Auth.ts#L36

We want to use an identity pool without specifying a user pool. Inside that identity pool we want to add 3 user pools as Cognito Authentication Providers. Is this possible?

**Comment by elorzafe** [comment]
@bharat-tiwari thanks for your feedback, I will take a look into that issue.

@vkulov If you want to use signIn, signUp with Amplify like `Auth.signIn(...)` you need to configure the userpool. Amplify currently supports only one userpool configure to do that. Cognito federated identities technically supports multiple User Pool but I never tried that with amplify. I can take a look to see if it works doing federatedSignIn.

**Comment by kingtut** [comment]
Also getting this error. User pool is not configured, would like to use Federated Identities only.

**Comment by sebastienfi** [comment]
Same as @vkulov here.

**Comment by elorzafe** [comment]
@kingtut @sebastienfi @vkulov I usually have that problem when is duplicated aws-amplify on my `node_modules` can you double check inside your app on `./node_modules/aws-amplify-react-native` if there is another `node_modules` with `aws-amplify` on it?

**Comment by sebastienfi** [comment]
```
C:\repos\app>yarn list --pattern "aws-*"
yarn list v1.13.0
warning Resolution field "apollo-cache-inmemory@1.5.1" is incompatible with requested version "apollo-cache-inmemory@1.3.10"
warning Resolution field "apollo-client@2.5.1" is incompatible with requested version "apollo-client@2.4.6"
warning Resolution field "graphql@14.1.1" is incompatible with requested version "graphql@^0.11.7"
warning Resolution field "@types/graphql@14.0.7" is incompatible with requested version "@types/graphql@0.12.6"
├─ @aws-amplify/auth@1.2.15
├─ @aws-amplify/cache@1.0.22
├─ @aws-amplify/core@1.0.22
├─ aws-api-gateway-client@0.2.16
├─ aws-appsync-react@1.2.6
├─ aws-appsync@1.7.1
├─ aws-sdk@2.329.0
└─ aws-sign2@0.7.0
Done in 0.29s.
```

**Comment by wstewartii** [comment]
I'm getting this issue as well. Is there a suggested workaround?

**Comment by lorensr** [comment]
Mine was fixed by going from:

```js
import Amplify from '@aws-amplify/core'
import config from './aws-exports'
Amplify.configure(config)
```

to

```js
import Amplify from 'aws-amplify'
import config from './aws-exports'
Amplify.configure(config)
```

**Comment by tafelito** [comment]
I tried @lorensr solution but did not work for me. I'm still getting the same issue. What I see is that even though I get the issue, the user is logged in anyway

**Comment by RoniqueRicketts** [comment]
I was going through this tutorial https://aws-amplify.github.io/docs/js/tutorials/building-react-native-apps/ and got the error mentioned about and I removed Auth by doing Amplify remove auth, after which I published the changes then re-add auth and I was able to get the application working. Have you tried that @bharat-tiwari

**Comment by mjmaix** [comment]
@lorensr worked for me.

**Comment by jordanranz** [comment]
@bharat-tiwari, any update on the responses above?

**Comment by ovidiumihaibelciug** [comment]
Updating the packages worked for me:

`npm update`
