### ISSUE TITLE
id field is not of type String, There was an error adding the API resource

### ISSUE THREAD

**Issue by AvneeshD** [aws-amplify/amplify-js#5211]
I'm using this guide,
https://aws-amplify.github.io/docs/js/start?ref=amplify-rn-btn&platform=react-native

I'm getting the error described in the title on step 3 of the tutorial. The following are the steps I took:

Do you want to configure advanced settings for the GraphQL API No, I am done.
Do you have an annotated GraphQL schema? No
Do you want a guided schema creation? Yes
What best describes your project: One-to-many relationship (e.g., “Blogs” with
 “Posts” and “Comments”)
Do you want to edit the schema now? No

**Comment by smn-snkl** [comment]
Having the same issue ...

**Comment by srobbin** [comment]
@AvneeshD, @smn-snkl  I think there's an error in the generated schema. Try changing `blogID: String!` to `blogID: ID!`

**Comment by marlonmarcello** [comment]
The default boilerplate generates it with the wrong type. Thanks @srobbin !

**Comment by jhockett** [comment]
Fixed the boilerplate in the Amplify CLI. Changes will be available in the next release. 

cc @sammartinez

**Comment by brene** [comment]
This seems to be fixed with @jhockett 's PR. @AvneeshD - please reopen this ticket if you can still reproduce.

**Comment by rpostulart** [comment]
@renebrandel I am still having this error with this schema and using @aws-amplify/cli version: 4.27.1
```

type Registration
  @model
  @key(name: "registrationByDate", fields: ["date"])
  # prettier-ignore
  @auth(
    rules: [
      {
        allow: owner,
        ownerField: "owner",
        operations: [create, update, delete, read]
      },
      { allow: private}
    ]
  ) {
  id: ID!
  horecaID: ID!
  horeca: Horeca! @connection(fields: ["horecaID"])
  members: [MemberRegistrations]
    @connection(keyName: "byRegistration", fields: ["id"])
  date: String!
  time: String!
  owner: String!
}

type Horeca
  @model
  @key(fields: ["id", "name"])
  @key(name: "horecaByName", fields: ["name", "place"])
  @key(name: "horecaByPlace", fields: ["place", "name"])
  # prettier-ignore
  @auth(rules: [{ allow: owner, ownerField: "owner",operations: [create, update, delete, read] },{ allow: private}]) {
  id: ID!
  name: String!
  place: String!
  qr: String
  owner: String!
  registrations: [Registration]
    @connection(keyName: "registrationByDate", fields: ["id"])
}

type Family
  @model
  @key(name: "byfamilyName", fields: ["familyName"])
  # prettier-ignore
  @auth(
    rules: [
      {
        allow: owner,
        ownerField: "owner",
        operations: [create, delete, update, read]
      },{ allow: private}
    ]
  ) {
  id: ID!
  familyName: String!
  address: String!
  phone: String!
  members: [Member]! @connection(keyName: "byName", fields: ["id"])
  owner: String!
}

type Member
  @model
  @key(name: "byName", fields: ["familyID", "name"])
  # prettier-ignore
  @auth(
    rules: [
      {
        allow: owner,
        ownerField: "owner",
        operations: [create, delete, update, read]
      },{ allow: private}
    ]
  ) {
  id: ID!
  familyID: ID!
  name: String!
  owner: String!
  family: Family @connection(fields: ["familyID"])
  registrations: [MemberRegistrations]
    @connection(keyName: "byMember", fields: ["id"])
}

type MemberRegistrations
  @model(queries: null)
  @key(name: "byMember", fields: ["memberID", "registrationID"])
  @key(name: "byRegistration", fields: ["registrationID", "memberID"]) {
  id: ID!
  registrationID: ID!
  memberID: ID!
  registrations: Registration! @connection(fields: ["registrationID"])
  members: Member! @connection(fields: ["memberID"])
}

```

**Comment by kannieWeesNie** [comment]
having the same problem.

here's my schema:

`type Customer @model {
  id: ID!
  name: String
  email: String
  phone: String
  physicalAddress: String
  deliveryAddress: String
  isRegistered: Boolean
  orders: [Order] @connection(keyName: "byOrder", fields: ["id"])
}

type Order @model @key(name: "byOrder", fields: ["customerId", "orderNumber"]){
  id: ID!
  date: String
  orderNumber: String!
  products: String
  customerId: String!
  instructions: String
}`

then when I run **amplify codegen models** I get the following:

`id field is not of type String
InvalidDirectiveError: id field is not of type String
    at checkFieldsAgainstIndex (C:\Users\Clive\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\graphql-connection-transformer\src\ModelConnectionTransformer.ts:119:11)
    at ModelConnectionTransformer.connectionWithKey (C:\Users\Clive\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\graphql-connection-transformer\src\ModelConnectionTransformer.ts:588:7)
    at ModelConnectionTransformer.field (C:\Users\Clive\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\graphql-connection-transformer\src\ModelConnectionTransformer.ts:226:12)
    at GraphQLTransform.transformField (C:\Users\Clive\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\graphql-transformer-core\src\GraphQLTransform.ts:376:25)
    at GraphQLTransform.transformObject (C:\Users\Clive\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\graphql-transformer-core\src\GraphQLTransform.ts:354:12)
    at GraphQLTransform.transform (C:\Users\Clive\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\graphql-transformer-core\src\GraphQLTransform.ts:270:18)
    at _buildProject (C:\Users\Clive\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\graphql-transformer-core\src\util\amplifyUtils.ts:108:35)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at ensureMissingStackMappings (C:\Users\Clive\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\graphql-transformer-core\src\util\amplifyUtils.ts:182:23)
    at Object.buildProject (C:\Users\Clive\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\graphql-transformer-core\src\util\amplifyUtils.ts:43:3)`

I am using amplify graphql API for a datastore in a vue app

Would greatly appreciate help overcoming this issue. thanks
