### ISSUE TITLE
Datastore not initiated when deployed to AWS Amplify hosting

### ISSUE THREAD

**Issue by rpostulart** [aws-amplify/amplify-js#5219]
I have build a Gatsby website with AWS Amplify datastore enabled. 

Locally it's working fine, but when deployed the datastore is not initiated. 

First load is showing an error:

`Uncaught (in promise) TypeError: Cannot read property 'version' of undefined
    at datastore.js:892
    at datastore.js:168
    at Object.next (datastore.js:98)
    at datastore.js:70
    at new Promise (<anonymous>)
    at F (datastore.js:49)
    at Ce (datastore.js:861)
    at datastore.js:606
    at datastore.js:168
    at Object.next (datastore.js:98)`

You can test here: log in with a random username and code (cccc). Then there is no indexDB initiated. When you refresh the page you see the indexDB is initiated and then it works. (login again)

By the way:
I have this in the index file

`DataStore.observe().subscribe(() => {})`

this is the url: https://master.d279mgdcgd53li.amplifyapp.com/

**Comment by rpostulart** [comment]
Seems like you have to init the datastore with listening to a real model.

So like: DataStore.observe().subscribe((MODEL) => {})

But on the index page I don't want to listen to anything so not sure if this is a bug or a need to change my requirements?

**Comment by emmafass** [comment]
@rpostulart I'm having the same issue. How did you solve this?

**Comment by emmafass** [comment]
> @rpostulart I'm having the same issue. How did you solve this?

solved with #7414

**Comment by rpostulart** [comment]
Sorry had no time yet to respond, but happy to see you solved it.

**Comment by dobeerman** [comment]
Still experiencing the issue with it.
Interesting behavior. If I add `console.log` around this line like this:

```js
console.warn('Start DataStore')
await DataStore.start()
console.warn('DataStore Started')
```

the second `console` output do not appears.

---

Framework: Vue3 with Composition API

**Comment by IanPhilips** [comment]
I was getting the same error as OP due to my `DataStore.start()` call in `_app.js`. Fixed it with [this](https://github.com/aws-amplify/amplify-js/issues/7414#issuecomment-790574704) suggestion: replacing `DataStore.start()` with `DataStore.query(YourModel)`.
