### ISSUE TITLE
DataStore - Sync error, subscription failed Connection failed: {"errors":[{"message":"Validation error of type FieldUndefined: Field 'blogDemoPostsId' in type 'PostDemo' is undefined @ 'onCreatePostDemo/blogDemoPostsId'"}]}

### ISSUE THREAD

**Issue by sim1camporeale** [aws-amplify/amplify-js#5407]
**Describe the bug**
When I try to query/observe and save an object into the datastore I get following error:
```
[WARN] 55:26.322 DataStore - Sync error, subscription failed Connection failed: {"errors":[{"message":"Validation error of type FieldUndefined: Field 'blogDemoPostsId' in type 'PostDemo' is undefined @ 'onCreatePostDemo/blogDemoPostsId'"}]}
- node_modules/expo/build/environment/muteWarnings.fx.js:18:23 in warn
* [native code]:null in warn
* http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:124726:12 in <unknown>
* http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:124759:22 in <unknown>
- node_modules/@aws-amplify/datastore/lib-esm/datastore/datastore.js:638:35 in sync.start.subscribe$argument_0.error
- node_modules/zen-observable/lib/Observable.js:139:8 in notifySubscription
* http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:129431:23 in onNotify
- node_modules/zen-observable/lib/Observable.js:239:11 in error
- node_modules/@aws-amplify/datastore/lib-esm/sync/index.js:141:56 in __generator$argument_1
* http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:126332:27 in step
- node_modules/tslib/tslib.js:120:34 in <anonymous>
- node_modules/tslib/tslib.js:111:43 in rejected
- node_modules/promise/setimmediate/core.js:37:14 in tryCallOne
- node_modules/promise/setimmediate/core.js:123:25 in setImmediate$argument_0
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:146:14 in _callTimer
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:194:17 in _callImmediatesPass
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:458:30 in callImmediates
* [native code]:null in callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:407:6 in __callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:143:6 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:142:17 in __guard$argument_0
* [native code]:null in flushedQueue
* [native code]:null in callFunctionReturnFlushedQueue
```

I get this error when I interact with DataStore with this snippet:
```
const testDataStore = (username: string) => {
  DataStore.query(BlogDemo)
    .then((data) => {
      console.log(data);
      DataStore.observe(BlogDemo).subscribe((event) => {
        console.log("=======SUB======");
        console.log(event);
      });
      let blog = new BlogDemo({
        name: "testBlog",
        posts: [],
        editors: [username],
      });
      console.log("save blog post");
      DataStore.save(blog);
    })
    .catch((err) => console.log(err));
};
```

**To Reproduce**

- Initialised a new project with Expo SDK 37.0.0 and Amplify Cli 4.18.0 and aws-amplify 3.0.7 and @aws-amplify/pubsub 3.0.7.
- added api, and auth.
- used provided schema for Blog, Posts and Comment.
- **amplify codegen** I get the error (argument must be a string)
- fixed the model and pushed changes with **amplify push**
- ran **amplify codegen models** that gives me an error saying that I can't use keyName in connection.
- removed all connection and keys from the schema obtaining the following schema:

```
type BlogDemo @model @auth(rules: [{ allow: owner, ownerField: "editors" }]) {
  id: ID!
  name: String!
  posts: [PostDemo] @connection
  editors: [String]!
}

type PostDemo @model @auth(rules: [{ allow: owner, ownerField: "editors" }]) {
  id: ID!
  title: String!
  blog: BlogDemo @connection
  comments: [CommentDemo] @connection
  editors: [String]!
}

type CommentDemo
  @model
  @auth(rules: [{ allow: owner, ownerField: "editors" }]) {
  id: ID!
  post: PostDemo @connection
  content: String!
  editors: [String]!
}
```
I added owners attributes as an Array su support multiple oweners.

**Expected behavior**
DataStore works without any error. And I can save/query and subscribe to Models.

<details>
  <summary><strong>Environment</strong></summary>

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages

  System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 519.36 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.12.0 - /usr/local/bin/node
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.92
    Firefox: 75.0
    Safari: 13.1
  npmPackages:
    @aws-amplify/pubsub: ^3.0.7 => 3.0.7
    @babel/core: ^7.8.6 => 7.9.0
    @react-native-community/netinfo: 5.5.1 => 5.5.1
    @types/react: ~16.9.23 => 16.9.34
    @types/react-native: ~0.61.17 => 0.61.23
    aws-amplify: ^3.0.7 => 3.0.7
    babel-preset-expo: ~8.1.0 => 8.1.0
    expo: ~37.0.3 => 37.0.7
    react: ~16.9.0 => 16.9.0
    react-dom: ~16.9.0 => 16.9.0
    react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
    react-native-screens: ~2.2.0 => 2.2.0
    react-native-web: ~0.11.7 => 0.11.7
    typescript: ~3.8.3 => 3.8.3
  npmGlobalPackages:
    @aws-amplify/cli: 4.18.0
    expo-cli: 3.17.24
    npm: 6.14.4
    react-native-cli: 2.0.1
```

</details>

**Smartphone (please complete the following information):**

- Device: iPhone8 - Simulator
- OS: iOS13.4
- Client: Expo 37

**Sample Log**
```
Array []
save blog post
[INFO] 05:38.220 Reachability - subscribing to reachability
[INFO] 05:38.233 Reachability - Notifying initial reachability state null
=======SUB======
Object {
  "condition": undefined,
  "element": BlogDemo {
    "_deleted": undefined,
    "_lastChangedAt": undefined,
    "_version": undefined,
    "editors": Array [
      "5c95f0eb-4662-4019-94e7-5ae073fed854",
    ],
    "id": "ab07dcf1-9c14-44cf-a142-8c0115e700e3",
    "name": "testBlog",
    "posts": Array [],
  },
  "model": [Function BlogDemo],
  "opType": "INSERT",
}
[INFO] 05:40.224 Reachability - Notifying reachability change true

[WARN] 05:40.894 DataStore - Sync error, subscription failed Connection failed: {"errors":[{"message":"Validation error of type FieldUndefined: Field 'blogDemoPostsId' in type 'PostDemo' is undefined @ 'onCreatePostDemo/blogDemoPostsId'"}]}
- node_modules/expo/build/environment/muteWarnings.fx.js:18:23 in warn
* [native code]:null in warn
* http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:124726:12 in <unknown>
* http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:124759:22 in <unknown>
- node_modules/@aws-amplify/datastore/lib-esm/datastore/datastore.js:638:35 in sync.start.subscribe$argument_0.error
- node_modules/zen-observable/lib/Observable.js:139:8 in notifySubscription
* http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:129431:23 in onNotify
- node_modules/zen-observable/lib/Observable.js:239:11 in error
- node_modules/@aws-amplify/datastore/lib-esm/sync/index.js:141:56 in __generator$argument_1
* http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:126332:27 in step
- node_modules/tslib/tslib.js:120:34 in <anonymous>
- node_modules/tslib/tslib.js:111:43 in rejected
- node_modules/promise/setimmediate/core.js:37:14 in tryCallOne
- node_modules/promise/setimmediate/core.js:123:25 in setImmediate$argument_0
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:146:14 in _callTimer
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:194:17 in _callImmediatesPass
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:458:30 in callImmediates
* [native code]:null in callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:407:6 in __callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:143:6 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:142:17 in __guard$argument_0
* [native code]:null in flushedQueue
* [native code]:null in callFunctionReturnFlushedQueue
```

**Comment by Johnniexson** [comment]
I'm facing this same problem for some days now, and i'm still stuck here. Querying data form the datastore works perfectly well before syncing with cloud. But now it doesn't.
![amplify warning](https://user-images.githubusercontent.com/33484116/79338189-c3444880-7f1e-11ea-8222-b18a4ecc2fe6.jpg)

**Comment by sim1camporeale** [comment]
Hi I was able to go on...
Try doing the following:
Check Dependecies, use only these
* "@aws-amplify/pubsub": "^3.0.7",
* "@react-native-community/netinfo": "5.5.0",
* "aws-amplify": "^3.0.7",

aws-amplify already includes datastore.

Downgrade amplify cli 4.17.2
* npm install -g @aws-amplify/cli@4.17.2

Install latest codegen modules from amplify 
* npm i -g @amplify-cli/amplify-codegen-appsync-model-plugin@1.15.0

Restore @connection using keyName and fields like this example:
```
type Blog
  @model
  @auth(
    rules: [
      {
        allow: groups
        groupsField: "editors"
        groupClaim: "email"
        operations: [create, update, delete, read]
      }
    ]
  ) {
  id: ID!
  name: String!
  posts: [Post] @connection(keyName: "byBlog", fields: ["id"])
  editors: [String]!
}

type Post
  @model
  @key(name: "byBlog", fields: ["blogID"])
  @auth(
    rules: [
      {
        allow: groups
        groupsField: "editors"
        groupClaim: "email"
        operations: [create, update, delete, read]
      }
    ]
  ) {
  id: ID!
  title: String!
  blogID: ID!
  blog: Blog @connection(fields: ["blogID"])
  comments: [Comment] @connection(keyName: "byPost", fields: ["id"])
  editors: [String]!
}

type Comment
  @model
  @key(name: "byPost", fields: ["postID", "content"])
  @auth(
    rules: [
      {
        allow: groups
        groupsField: "editors"
        groupClaim: "email"
        operations: [create, update, delete, read]
      }
    ]
  ) {
  id: ID!
  postID: ID!
  post: Post @connection(fields: ["postID"])
  content: String!
  editors: [String]!
}
```

so the bug is confirmed. I think that the issues are two:

* amplify-cli doesn't allow to use keyName but it is supported 
* amplify codegen model doesn't create correct model if we use @connection without keyName

**Comment by Johnniexson** [comment]
> * 3.0.7

Hi, do i still import DataStore from "@aws-amplify/DataStore" or can it be imported from "aws-amplify"

**Comment by sim1camporeale** [comment]
Hi aws-amplify is a meta package you can import 
* import DataStore from "@aws-amplify/DataStore"
using the metapackage you are sure that all dependencies are aligned

**Comment by Johnniexson** [comment]
@sim1camporeale how can i DM you? i have some questions to ask as regards ur Datastore use case in production. Thanks

**Comment by sim1camporeale** [comment]
Hi @Johnniexson yes feel free to DM me.
Sorry for late reply

**Comment by Johnniexson** [comment]
Hi @sim1camporeale  seems DM is not possible here on github

**Comment by sim1camporeale** [comment]
@Johnniexson  don't worry if your issue regards DataStore keep it public so someone else can take advantage of our discussion. So let me know what's going wrong.

**Comment by Johnniexson** [comment]
Okay, i'm a bit concerned about data security while using dataStore, since copy of the data are present in the device local storage, won't sensitive data be exposed to if someone goes to inspect the local db(indexDB)?

**Comment by Johnniexson** [comment]
Also, i have this issue with has one connection.

**Here is the schema type:**

```
type Connection @model @key(name: "bySender", fields: ["senderId"]) {
  id: ID!
  senderId: ID!
  recipientId: ID!
  sender: User @connection(fields: ["senderId"])
  recipient: User @connection(fields: ["recipientId"])
  status: Status!
  createdAt: String
}
```

when i ran `amplify codegen models`, senderId and recipientId fields are missing in the model.
**Here is the generated model:**

```
export declare class Connection {
  readonly id: string;
  readonly sender?: User;
  readonly recipient?: User;
  readonly status: Status | keyof typeof Status;
  readonly createdAt?: string;
  constructor(init: ModelInit<Connection>);
  static copyOf(source: Connection, mutator: (draft: MutableModel<Connection>) => MutableModel<Connection> | void): Connection;
}
```

**_Any reason for this behaviour??_**

**Comment by sim1camporeale** [comment]
What kind of sensitive data do you plan to store inside the device local storage?
Anyway by default, data stored on the device is protected by the on-device encryption when it is locked. So unless the attacker has the device passcode they cannot access the data at rest.

**Comment by Johnniexson** [comment]
Okay, any idea about the issue above?

**Comment by sim1camporeale** [comment]
I think it is correct.
Using connection you'll handle the model manipulation classes and ignoring id.
Than Datastore will generate and use id when needed.
In this way you can add an User as recipient and another user ad sender.

Take into account to rename Connection class to avoid name clashes and confusion.

**Comment by Johnniexson** [comment]
> I think it is correct.
> Using connection you'll handle the model manipulation classes and ignoring id.
> Than Datastore will generate and use id when needed.
> In this way you can add an User as recipient and another user ad sender.
> 
> Take into account to rename Connection class to avoid name clashes and confusion.

But the problem is that when i need to create new connection using Datastore.save(), I can't set the senderId and recipientId field since they are required field and are missing in the model generated. 🤦‍♂️

**Comment by sim1camporeale** [comment]
Which are your dependencies? Can you attach your packages.json ?

**Comment by Johnniexson** [comment]
"@aws-amplify/core": "^2.2.5",
    "@aws-amplify/datastore": "^1.0.8",

> Which are your dependencies? Can you attach your packages.json ?

  "@aws-amplify/core": "^2.2.5",
   "@aws-amplify/datastore": "^1.0.8",
   "aws-amplify": "^3.0.7",
   "aws-amplify-angular": "^4.1.7",

**Comment by Johnniexson** [comment]
> Which are your dependencies? Can you attach your packages.json ?

```
"@aws-amplify/core": "^2.2.5",
"@aws-amplify/datastore": "^1.0.8",
"aws-amplify": "^3.0.7",
"aws-amplify-angular": "^4.1.7",
```

**Comment by sim1camporeale** [comment]
feel free to remove core and datastore dependecies.
Use only these 
```
"@aws-amplify/pubsub": "^3.0.7",
 "@react-native-community/netinfo": "5.5.1",
 "aws-amplify": "^3.0.7",
```
Be sure to sue amplify cli 4.18

**Comment by Johnniexson** [comment]
> feel free to remove core and datastore dependecies.
> Use only these
> 
> ```
> "@aws-amplify/pubsub": "^3.0.7",
>  "@react-native-community/netinfo": "5.5.1",
>  "aws-amplify": "^3.0.7",
> ```
> 
> Be sure to sue amplify cli 4.18

Using this, how do i then import dataStore in my component?? 

Also, is it ideal to use Datastore with Appsync (knowing that Datastore saves data in device local storage engine before sync) for a banking or payment app instead of using graphqlOperations from amplify api ?

**Comment by sim1camporeale** [comment]
Sorry be sure to use Amplify CLI 4.17.2
aws-amplify is a meta package that includes DataStore.
So you can import as you are already doing.

**Comment by manueliglesias** [comment]
Hi @sim1camporeale 

Looks like you were able to find a solution to your problem. I am going to close this issue, please feel free to open a new one if new issues come up

**Comment by sim1camporeale** [comment]
@manueliglesias issue isn’t solved. I had to downgrade both amplify and data store to be let things work. I’ll retry with latest cli and data store and I’ll let you know if issue persists

**Comment by sim1camporeale** [comment]
. I think that the issues are two:

* amplify-cli doesn't allow to use keyName but it is supported
* amplify codegen model doesn't create correct model if we use @connection without keyName

**Comment by undefobj** [comment]
> . I think that the issues are two:
> 
> * amplify-cli doesn't allow to use keyName but it is supported
> * amplify codegen model doesn't create correct model if we use @connection without keyName

@sim1camporeale can you download the latest CLI and walk through the docs for relational modeling with DataStore? We released an updated CLI relaxing the keyName restriction and updated docs a week ago.

**Comment by brataaaan** [comment]
Hey @manueliglesias ,

can you please describe how you managed to solve this problem? :-)

**Comment by sim1camporeale** [comment]
@undefobj  I'll retry updating amplify cli and amplify depndecny to latest version and let you know if issue persists. Can you share the reference verisons?

**Comment by sim1camporeale** [comment]
I confirm that with latest version everything works.

**Comment by JaredJacobsen** [comment]
I've been having the same problem with version 4.29.1, but it seems to work when I pass `name` to `@connection` rather than `keyName`, following [this](https://docs.amplify.aws/cli/graphql-transformer/overview#create-a-graphql-api) example:
```
 type Blog @model {
  id: ID!
  name: String!
  posts: [Post] @connection(name: "BlogPosts")
}
type Post @model {
  id: ID!
  title: String!
  blog: Blog @connection(name: "BlogPosts")
  comments: [Comment] @connection(name: "PostComments")
}
type Comment @model {
  id: ID!
  content: String
  post: Post @connection(name: "PostComments")
}
```
I don't understand why the [documentation](https://docs.amplify.aws/cli/graphql-transformer/directives#connection) for `@connection` doesn't mention that you can use `name`
