### ISSUE TITLE
Storage - PUT https://localhost/buck-storage net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by HamzaLJ** [aws-amplify/amplify-js#5608]
**Describe the bug**
I've added Storage to my project; however, when trying to upload a file I get the following errors :

```
POST https://localhost/ net::ERR_CONNECTION_REFUSED

[ERROR] 40:12.548 axios-http-handler Error: Network Error
    at createError (createError.js:16)

[WARN] 40:12.550 AWSS3Provider - error uploading Error: Network Error

zone-evergreen.js:2952 PUT https://localhost/buck-storage-bucket23455559-production/public/file.jpg?x-id=PutObject net::ERR_CONNECTION_REFUSED
```

**To Reproduce**
Simply follow the official docs : https://docs.amplify.aws/lib/storage/getting-started/q/platform/js

Then, run it locally and try to upload a file.

**Expected behavior**
It should upload to s3, not http://localhost

**Code Snippet**

**main.component.html**

`
<amplify-photo-picker [storageOptions]="{'level': 'public'}" (picked)="onImagePicked($event)">
 </amplify-photo-picker>
`

**main.component.ts**

```
  async onImagePicked(file) {
    const key = `pics/${file.name}`;
    this.amplify.storage().put( key, file, {
      contentType: file.type
    })
    .then (result => console.log('uploaded: ', result))
    .catch(err => console.log('upload error: ', err));
    }
```

**Screenshots**

<img src="https://i.ibb.co/X2TvmFx/Screen-Shot-2020-04-28-at-22-51-05.jpg"></img>

**aws-exports** file:

   ```
const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://xxxxx.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-xxxxxxxx",
    "aws_cognito_identity_pool_id": "eu-west-2:xxxxxxxx-832f-aaaaaa-900a-xxxxxxx",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2-xxxxxxxxx",
    "aws_user_pools_web_client_id": "xxxxx8x8x88x8x8x8x",
    "oauth": {},
    "aws_user_files_s3_bucket": "xxxxx-storage-xxxxxxxxx-production",
    "aws_user_files_s3_bucket_region": "eu-west-2"
};
 
**System:**

```
    OS: macOS Mojave 10.14.6
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.2 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/Documents/Z/XXXX/node_modules/.bin/yarn
    npm: 6.14.4 - ~/.npm-packages/bin/npm
  Browsers:
    Chrome: 81.0.4044.129
    Firefox: 75.0
    Safari: 13.1
  npmPackages:
    @angular-devkit/build-angular: ~0.803.23 => 0.803.26 
    @angular/animations: ~8.2.14 => 8.2.14 
    @angular/cli: ~8.3.23 => 8.3.26 
    @angular/common: ~8.2.14 => 8.2.14 
    @angular/compiler: ~8.2.14 => 8.2.14 
    @angular/compiler-cli: ~8.2.14 => 8.2.14 
    @angular/core: ~8.2.14 => 8.2.14 
    @angular/forms: ~8.2.14 => 8.2.14 
    @angular/language-service: ~8.2.14 => 8.2.14 
    @angular/platform-browser: ~8.2.14 => 8.2.14 
    @angular/platform-browser-dynamic: ~8.2.14 => 8.2.14 
    @angular/router: ~8.2.14 => 8.2.14 
    @aws-amplify/ui: ^2.0.2 => 2.0.2 
    @types/jasmine: ~3.3.8 => 3.3.16 
    @types/jasminewd2: ~2.0.3 => 2.0.8 
    @types/node: ~8.9.4 => 8.9.5 
    aws-amplify: ^3.0.9 => 3.0.9 
    aws-amplify-angular: ^5.0.8 => 5.0.8 
    codelyzer: ^5.0.0 => 5.2.2 
    jasmine-core: ~3.4.0 => 3.4.0 
    jasmine-spec-reporter: ~4.2.1 => 4.2.1 
    karma: ~4.1.0 => 4.1.0 
    karma-chrome-launcher: ~2.2.0 => 2.2.0 
    karma-coverage-istanbul-reporter: ~2.0.1 => 2.0.6 
    karma-jasmine: ~2.0.1 => 2.0.1 
    karma-jasmine-html-reporter: ^1.4.0 => 1.5.3 
    protractor: ~5.4.0 => 5.4.4 
    rxjs: ~6.4.0 => 6.4.0 
    ts-node: ~7.0.0 => 7.0.1 
    tslib: ^1.10.0 => 1.11.1 
    tslint: ~5.15.0 => 5.15.0 
    typescript: ~3.5.3 => 3.5.3 
    yarn: ^1.22.4 => 1.22.4 
    zone.js: ~0.9.1 => 0.9.1 
  npmGlobalPackages:
    @angular/cli: 8.3.23
    @angular/core: 5.2.2
    @aws-amplify/cli: 4.18.0
    angular: 1.5.7
    bower: 1.8.8
    brunch: 2.10.12
    cordova-res: 0.8.1
    cordova: 7.1.0
    gulp-cli: 2.2.0
    gulp: 4.0.0
    http-server: 0.11.1
    ionic: 5.4.16
    ios-deploy: 1.9.2
    ios-sim: 6.0.0
    n: 2.1.12
    native-run: 0.3.0
    npm-check-updates: 2.14.2
    npm: 6.14.4
    to: 0.2.9
    update: 0.7.4
    yarnpkg: 0.15.1
```

**Comment by Amplifiyer** [comment]
@HamzaLJ this has been resolved already, can you try deleting your lock files and node_modules and try again?

**Comment by HamzaLJ** [comment]
@Amplifiyer I ran `rm -rf node_modules` however, still getting the same error.

**Comment by Amplifiyer** [comment]
> 
> 
> @Amplifiyer I ran `rm -rf node_modules` however, still getting the same error.

@HamzaLJ Just to confirm, you also deleted your lock files?

**Comment by HamzaLJ** [comment]
@Amplifiyer I deleted `package-lock.json` I have no lock files

**Comment by HamzaLJ** [comment]
@Amplifiyer After deleting `package-lock.json` as well as `node_modules` it worked.
Thanks for the suggestion.
