### ISSUE TITLE
Axios error when uploading blob file to s3 with aws amplify react native v3.0.12

### ISSUE THREAD

**Issue by thekrol01** [aws-amplify/amplify-js#5903]
**Describe the bug**

When I upload a file from react native app with PUT S3 I get an Axios error with statuscode 403. 
I use version: "aws-amplify": "^3.0.12",

The same AWS configuration is running in a production environment with aws-amplify 2.7.0 and works.
**To Reproduce**

I use an identity pool to access the bucket:

import Amplify, { Auth, Storage, API } from 'aws-amplify';
Amplify.configure({
Storage:{
         {
          Auth: {
          identityPoolId: 'XXXXXX',
          region: 'XXXXX',
        },
        Storage:{
          AWSS3: {
          bucket: 'XXXXXX',
          identityPoolId: 'XXXXXX',
          region: 'XXXX,
        }
      }
})

*Expected behavior**
Upload S3 image

system:

  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 440.00 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.3.0 - /usr/local/bin/node
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 81.0.4044.138
    Safari: 13.1
  npmPackages:
    @babel/core: ^7.6.2 => 7.9.6 
    @babel/runtime: ^7.6.2 => 7.9.6 
    @react-native-community/async-storage: ^1.7.1 => 1.11.0 
    @react-native-community/eslint-config: ^0.0.5 => 0.0.5 
    @react-native-community/masked-view: ^0.1.6 => 0.1.10 
    @react-native-community/netinfo: ^5.6.2 => 5.9.1 
    @react-native-community/push-notification-ios: ^1.0.5 => 1.2.0 
    @react-native-community/slider: ^2.0.8 => 2.0.9 
    @react-navigation/native: ^5.0.0 => 5.4.3 
    @react-navigation/stack: ^5.0.0 => 5.4.0 
    @sentry/react-native: ^1.4.0 => 1.4.0 
    aws-amplify: ^3.0.12 => 3.0.12 
    babel-jest: ^24.9.0 => 24.9.0 
    base-64: ^0.1.0 => 0.1.0 
    eslint: ^6.5.1 => 6.8.0 
    expo-av: ^8.0.0 => 8.1.0 
    expo-barcode-scanner: ^8.0.0 => 8.1.0 
    expo-camera: ^8.0.0 => 8.2.0 
    expo-image-manipulator: ^8.0.0 => 8.1.0 
    expo-image-picker: ^8.0.2 => 8.1.0 
    expo-location: ^8.0.0 => 8.1.0 
    expo-secure-store: ^8.0.0 => 8.1.0 
    firebase: ^7.14.5 => 7.14.5 
    geolib: ^3.2.1 => 3.3.1 
    jest: ^24.9.0 => 24.9.0 
    metro-react-native-babel-preset: ^0.56.0 => 0.56.4 
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4 
    react-native-background-fetch: ^2.7.1 => 2.8.0 
    react-native-gesture-handler: ^1.5.6 => 1.6.1 
    react-native-image-pan-zoom: ^2.1.11 => 2.1.12 
    react-native-maps: 0.27.1 => 0.27.1 
    react-native-purchases: ^3.0.6 => 3.2.0 
    react-native-push-notification: ^3.1.9 => 3.5.2 
    react-native-qrcode-svg: ^6.0.3 => 6.0.6 
    react-native-reanimated: ^1.7.0 => 1.9.0 
    react-native-safe-area-context: ^0.7.0 => 0.7.3 
    react-native-screens: ^2.0.0-beta.2 => 2.8.0 
    react-native-svg: ^11.0.1 => 11.0.1 
    react-native-unimodules: ^0.7.0 => 0.7.0 
    react-native-vector-icons: ^6.6.0 => 6.6.0 
    react-redux: ^7.1.3 => 7.2.0 
    react-test-renderer: 16.9.0 => 16.9.0 
    redux: ^4.0.5 => 4.0.5 
    redux-thunk: ^2.3.0 => 2.3.0 
    validate.js: ^0.13.1 => 0.13.1 
  npmGlobalPackages:
    expo-cli: 3.13.1
    npm: 6.14.4

**Comment by thekrol01** [comment]
the Sentry breadcrumbs:

xhr | POST https://cognito-identity.eu-west-1.amazonaws.com/ [200]

xhr |PUT https://XXXXXX.s3.eu-west-1.amazonaws.com/public/posts/1590506382416kCLQ5RxMHDgwkJ6YFYfqprgSgu72.jpg?x-id=PutObject [403]

[ERROR] 19:43.363 axios-http-handler Error: Request failed with status code 403

**Comment by iartemiev** [comment]
We just released a fix for this in aws-amplify@3.0.13. 
Please give that a try and let us know if it's solved the issue for you.

**Comment by iartemiev** [comment]
Closing, as this seems to be related to https://github.com/aws-amplify/amplify-js/issues/5873 which has been solved in the latest version of Amplify

**Comment by thekrol01** [comment]
Installed the 3.0.13 version and still get the error unfortunately.

**Comment by manhncse02926** [comment]
I still get the error on version 3.0.17.

**Comment by avlonder** [comment]
On 3.0.18 as well

**Comment by bneigher** [comment]
version 3 has been out for several months and I still can't upgrade from aws-amplify 2.3.0 because of the terrible support for react-native.  what's going on with this library guys.

- can't use network inspect in RND
- 403 errors on endpoint PUT requests
- can't read / write to private s3 with storage.

Is there a v2 to v3 upgrade that I missed?  or is everyone else also not using v3 yet...

**Comment by FadiAboMsalam** [comment]
Same here on "aws-amplify": "^3.0.22",

**Comment by Reenagrg100** [comment]
Hey, I'm still facing this issue in 3.1.0. Any update on this?

**Comment by ertomz** [comment]
Hello! I'm currently having this issue with aws-amplify "^3.3.10". Has anyone here found a working solution?

**Comment by Reenagrg100** [comment]
> Hello! I'm currently having this issue with aws-amplify "^3.3.10". Has anyone here found a working solution?

Hey, I upgraded my React native version from 0.62.4 to 0.63.3 and it worked perfectly for me on both android and iOS.

**Comment by ertomz** [comment]
> > Hello! I'm currently having this issue with aws-amplify "^3.3.10". Has anyone here found a working solution?
> 
> Hey, I upgraded my React native version from 0.62.4 to 0.63.3 and it worked perfectly for me on both android and iOS.

Thank you @Reenagrg100 !!! So simple, but worked like a charm. I ran expo update in my terminal. 

Now that I'm on here, I'm running into another issue uploading an image to S3:

`[WARN] 05:25.12 AWSS3Provider - error uploading, [TypeError: undefined is not an object (evaluating 'data.byteLength')]`

Any advice would be much appreciated. :)

**Comment by MedElba** [comment]
> > > Hello! I'm currently having this issue with aws-amplify "^3.3.10". Has anyone here found a working solution?
> > 
> > 
> > Hey, I upgraded my React native version from 0.62.4 to 0.63.3 and it worked perfectly for me on both android and iOS.
> 
> Thank you @Reenagrg100 !!! So simple, but worked like a charm. I ran expo update in my terminal.
> 
> Now that I'm on here, I'm running into another issue uploading an image to S3:
> 
> `[WARN] 05:25.12 AWSS3Provider - error uploading, [TypeError: undefined is not an object (evaluating 'data.byteLength')]`
> 
> Any advice would be much appreciated. :)

Hello, I have same problem in my React Native app, both for reading and uploading! Using react native 0.63.3 and aws-amplify 3.3.15.

Did you solve?
Thanks!!

**Comment by ertomz** [comment]
Hi @MedElba ,

Unfortunately, no. I'm now having the same axios error, even after updating my expo once again. Let me know if you find a solution to this!

(Here are what my errors looks like)
```
axios-http-handler, [Error: Request failed with status code 403]
AWSS3Provider - error uploading, [Error: Request failed with status code 403]
```

**Comment by MedElba** [comment]
> Hi @MedElba ,
> 
> Unfortunately, no. I'm now having the same axios error, even after updating my expo once again. Let me know if you find a solution to this!
> 
> (Here are what my errors looks like)
> 
> ```
> axios-http-handler, [Error: Request failed with status code 403]
> AWSS3Provider - error uploading, [Error: Request failed with status code 403]
> ```

Hi! For now it is working for me only for uploading! 
Listing and getFile is 403. I'll let you know if I will resolve it on the console!

**Comment by ertomz** [comment]
@MedElba 

It works for you for uploading? Could you send the code for how you're doing it? 
Thank you!

**Comment by ngocketit** [comment]
If you have a user who is assigned to a group created via `amplify auth update`, make sure you grant the group needed permissions for the storage since the group role that user assumes will be created and by default, it has no permission.

**Comment by MedElba** [comment]
From what I've seen on the community, it is a sort of "bug" in the amplify sdk, since when logging out with cognito doesn't always clear the tokens stored in the async storage; that's why happens sometimes the 403 error. For me in my react native app, sometimes  solves uninstalling and reinstalling the app but stil struggling to find a working solution! (this happens to me using both API Gateway and S3 storage)

**Comment by gulsher7** [comment]
i'm facing same problem anyone found solution ?

**Comment by felixolivares** [comment]
I had this same problem when uploading/listing files: axios-http-handler Error: Request failed with status code 403. I went  through all the related issues and tried all posible solutions and couldn't make it work. But then I tried something different, I knew it was a permissions error so I went again to the configuration: `amplify storage configure` and selected Both for the Auth/Guests Users and Individual Groups in the "Restrict access by" option, selected the permissions for each group I had and voilà, it worked! Just my two cents for this in case somebody is still having this issue.

**Comment by shichi18** [comment]
https://github.com/aws-amplify/amplify-js/issues/5903#issuecomment-979714391

> I had this same problem when uploading/listing files: axios-http-handler Error: Request failed with status code 403. I went through all the related issues and tried all posible solutions and couldn't make it work. But then I tried something different, I knew it was a permissions error so I went again to the configuration: `amplify storage configure` and selected Both for the Auth/Guests Users and Individual Groups in the "Restrict access by" option, selected the permissions for each group I had and voilà, it worked! Just my two cents for this in case somebody is still having this issue.


Thank you!
It was solved in my project.

**Comment by majirosstefan** [comment]
I think this issue should not be closed, (or be re-opened) as I am experiencing this when running amplify mock with amplify ˆ3.1.1 and "aws-amplify-react-native": "^4.2.5".

**Comment by NiksanJP** [comment]
Any updates?
