### ISSUE TITLE
How to customize PreSignup error response text in amplify-authenticator

### ISSUE THREAD

**Issue by kjetilge** [aws-amplify/amplify-js#5911]
**Category** 

Auth

**Amplify CLI Version** 

```amplify --version
4.20.0
```

This is a Vuejs app.

My PreSignup handler ends with the following:

```
  if (!allowed) {
    callback("My error message", null);
  } else {
    callback(null, event);
  }
```

When I run: ```mock function myPreSignup```

Output is:

```
myPreSignup failed with the following error:
{ '0': 'M',
  '1': 'y',
  '2': ' ',
  '3': 'e',
  '4': 'r',
  '5': 'r',
  '6': 'o',
  '7': 'r',
  '8': ' ',
  '9': 'm',
  '10': 'e',
  '11': 's',
  '12': 's',
  '13': 'a',
  '14': 'g',
  '15': 'e' }
```

However in the browser the following is displayed in the amplify-toast:
> myPreSignup failed with the following error: My error message

How do I remove or change (or preferably translate using i18) the text: "myPreSignup failed with the following error:" ?

I have also tried something like this in my handler:
```
  if (!allowed) {
    callback({error: 'My error message'}, null);
  } else {
    callback(null, event);
  }
```

When I try mocking I get this output:
```
myPreSignup failed with the following error:
{ error: 'My error message' }
```

Then the coresponding message in the browser amplify-toast is something like:
> myPreSignup failed with the following error: [object, object]

Which is not very usefull

What is the correct way of dealing with this ?
Is it perhaps possible to overide the signUp() function ?
And shouldn't the mocking output error text look more like the toast output ? (Now it's confusing)

**Comment by ashika01** [comment]
@kjetilge - Could you let us know which package you are using for UI?

**Comment by kjetilge** [comment]
I'm using [Vue](https://docs.amplify.aws/ui/q/framework/vue)

**Comment by kjetilge** [comment]
> @kjetilge The callback function for mock expects an error object here https://github.com/aws-amplify/amplify-cli/blob/858112e75fab7628b9a0f9cd95c08ff571dc707d/packages/amplify-util-mock/src/utils/lambda/execute.ts#L38
> 

If I use an error-object I will get a useless message in the amplify-tost. As mentioned above tihis results in the message: myPreSignup failed with the following error: [object, object]

I should be able to somehow override the message "myPreSignup failed with the following error:" 
b/c the mock output should mirror what is diaplyed in amplify-toast, not ?

**Comment by ashika01** [comment]
Making sure again, the link you have point to `@aws-amplify/ui-vue`. So if you are using that, you might not be able to change the error message. We started having discussions on this internally. we can mark this issue as Feature request and track the progress in this as we go along.

Workaround would be for you to create your custom UI using slots and pass the needed error message to amplify-toast component. [Docs are here](https://docs.amplify.aws/ui/auth/authenticator/q/framework/vue#customization)

**Comment by ashika01** [comment]
I dont completely understand your use case yet. Would it be possible to stringify the error object in case of failure so it shows up properly in toast?

**Comment by kjetilge** [comment]
In I'm short I'm translating to norwegian.

**Comment by kjetilge** [comment]
I'll try to do your suggested workaround for now.
At least the front-end now has [Norwgian translation](https://github.com/kjetilge/amplify-auth-norwegian-bokmaal/blob/master/norwegian.js) 😀

**Comment by ashika01** [comment]
Yeah, we are basically looking at making use of i18n that we have to do this. So will keep you posted here.

**Comment by kjetilge** [comment]
Is it possible to use thy context.fail for anything ?

**Comment by ashika01** [comment]
What do you mean by context.fail?

**Comment by kjetilge** [comment]
In your code I see:
```

    const context = {
      done(error, result) {
        if (!returned) {
          returned = true;
          if (error === null || typeof error === 'undefined') {
            context.succeed(result);
          } else {
            context.fail(error);
          }
        }
      },
```

**Comment by ashika01** [comment]
@ammarkarachi any thoughts?

**Comment by ashika01** [comment]
I see above this is your sample code,

```
if (!allowed) {
    callback({error: 'My error message'}, null);
  } else {
    callback(null, event);
  }
```

I was suggesting this, which should solve the toast problem

```
if (!allowed) {
    callback(JSON.stringify({error: 'My error message'}), null);
  } else {
    callback(null, event);
  }
```

**Comment by ammarkarachi** [comment]
If I understand correctly you want to intercept the error message to translate it?

**Comment by kjetilge** [comment]
I see, but I would still get the "myPreSignup failed with the following error:" in front of my message ?

**Comment by kjetilge** [comment]
Yes. I want to intercept the error message for translatiopn.

**Comment by kjetilge** [comment]
It is a litlle strange that passing values to [validationErrors](https://docs.amplify.aws/ui/auth/authenticator/q/framework/vue#sign-up) SignUp in Vue UI component in does not fix this.

**Comment by ashika01** [comment]
@kjetilge Yeah.. So now we use StencilJS to build our core UI and use [stencil bindings](https://github.com/ionic-team/stencil-ds-plugins) to generate different framework's code. So some functionality might be missing.

**Comment by man-andy** [comment]
Any update on this?
