### ISSUE TITLE
Fully typed hubs

### ISSUE THREAD

**Issue by arlyon** [aws-amplify/amplify-js#5997]
**Describe the solution you'd like**

Currently there is nothing in the way of typing for hubs. I would like my IDE / editor to know based on the type of the event which parameters I am expected to pass it. So, a hub is configured with a number of known events at compile time, each with expected payloads. It may look something like this:

```ts
type PagePayload = {
  event: "page";
  data: { pageId: string };
  message: string;
};

type WelcomeFlowPayload = {
  event: "welcome-flow";
  data: { time: number };
  message: string;
};

type HubPayload = PagePayload | WelcomeFlowPayload;

type HubCallback<T extends HubPayload> = (
  capsule: HubCapsule<T>
) => void | Promise<void>;

type HubCapsule<T extends HubPayload> = {
  channel: string;
  payload: T;
  source: string;
  patternInfo?: string[];
};

/**
 * Listens to page events and publishes analytics
 * from them.
 */
const pageAnalytics: HubCallback<PagePayload> = ({ payload }) => {
  console.log(payload.data.pageId);
};
```

**Describe alternatives you've considered**

I've considered other event-bus type libraries such as Dashlane/ts-event-bus however I'd like to avoid adding unneeded bundle size. Given the recent move to typescript this seems an opportune time.

**Comment by arlyon** [comment]
As an addendum, here is a simple wrapper around Hub that adds type information:

```ts
class TypedHubClass<T extends { [key: string]: HubPayload }> {
  private hub: HubClass;

  constructor(hub: HubClass) {
    this.hub = hub;
  }

  listen<K extends keyof T, V extends T[K]>(
    channel: K,
    callback?: HubCallback<V>,
    listenerName?: string
  ) {
    // @ts-ignore
    // eslint-disable-next-line
    this.hub.listen(channel, callback, listenerName);
  }

  remove<K extends keyof T, V extends T[K]>(
    channel: K,
    callback?: HubCallback<V>
  ) {
    // @ts-ignore
    // eslint-disable-next-line
    this.hub.remove(channel, callback);
  }

  dispatch<K extends keyof T, V extends T[K]>(
    channel: K,
    payload: V,
    source = "",
    ampSymbol?: symbol
  ) {
    // @ts-ignore
    this.hub.dispatch(channel, payload, source, ampSymbol);
  }
}

const TypedHub = new TypedHubClass<{
  page: PagePayload;
  "welcome-flow": WelcomeFlowPayload;
}>(Hub);
```

**Comment by ashika01** [comment]
@arlyon Would be interested in opening a PR for this? We could have someone in the team help you see this to closure.

**Comment by arlyon** [comment]
Yeah actually, that would be cool. I've got some free time this weekend so I'll take a crack at it. I'm not sure what the api would look like but as I see it amplify would come with a basic hub with the predefined channels built in, and users could 'update' it with their own channel types.

**Comment by jhechtf** [comment]
Has there been any traction on this? I was just trying to use the hub in a svelte application and was getting frustrated with not being able to get proper details for the events in the auth channel. I did some basic check with TypeScript discrimination to determine if it would be feasible and it appears like it should be.

**Comment by laclance** [comment]
what about using `import { HubCapsule } from '@aws-amplify/core';`

**Comment by stocaaro** [comment]
Related with #4817

**Comment by jimblanc** [comment]
We have published an RFC on our plan for improving TypeScript support in Amplify JS & would love to get your feedback & suggestions!

[RFC: Amplify JS TypeScript Improvements](https://github.com/aws-amplify/amplify-js/issues/11113)

**Comment by Nikola-Milovic** [comment]
How would RegExp be handled? Would they default to `any` for the payload type?

**Comment by cwomack** [comment]
The developer preview for v6 of Amplify has officially been released with improved support for TypeScript and much more! Please check out our [announcement](https://aws.amazon.com/blogs/mobile/aws-amplify-javascripts-new-developer-preview-with-reduced-bundle-sizes-improved-typescript-and-next-js-support/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=238088647) and updated [documentation](https://docs.amplify.aws/lib-v1/project-setup/create-application/q/platform/js/) to see what has changed.

This issue should be resolved within the dev preview and upcoming General Availability for Amplify v6, but let us know with a comment if there are further issues.

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.

**Comment by moyarich** [comment]
i am using amplify 6, and problem isn't fixed: I am getting this error:

**Generic type 'HubCapsule' requires 2 type argument(s).ts(2314)**


```typescript
(alias) type HubCapsule<Channel extends string, EventData extends EventDataMap> = {
    channel: Channel;
    payload: HubPayload<EventData>;
    source?: string | undefined;
    patternInfo?: string[] | undefined;
}
import HubCapsule
```

**Comment by rmjwilbur** [comment]
> With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.

Hi @cwomack 

I'm a little confused. I've seen other comments saying we should be using "aws-amplify/\*" and that "@aws-amplify/\*" is meant for internal use. If that's the case, how can we easily access HubPayload and other types without importing from "@aws-amplify" or resorting to workarounds, like:

`export type HubCallback = Parameters<(typeof Hub)['listen']>[1];
`
