### ISSUE TITLE
Require Cycle and Async Storage warning

### ISSUE THREAD

**Issue by ThatMate** [aws-amplify/amplify-js#6031]
I am using `aws-amplify@3.0.16` which is the latest at this point. I am using it for my React Native project. I am seeing two warnings:

```
[Sun Jun 07 2020 15:28:29.187]  WARN     Require cycle: node_modules/@aws-amplify/pubsub/lib-esm/index.js -> node_modules/@aws-amplify/pubsub/lib-esm/PubSub.js -> node_modules/@aws-amplify/pubsub/lib-esm/Providers/index.js -> node_modules/@aws-amplify/pubsub/lib-esm/Providers/AWSAppSyncRealTimeProvider.js -> node_modules/@aws-amplify/pubsub/lib-esm/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Sun Jun 07 2020 15:28:29.190]  WARN     Require cycle: node_modules/@aws-amplify/datastore/lib-esm/util.js -> node_modules/@aws-amplify/datastore/lib-esm/types.js -> node_modules/@aws-amplify/datastore/lib-esm/util.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
```

AND 

```
Warning: Async Storage has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/async-storage' instead of 'react-native'. See https://github.com/react-native-community/react-native-async-storage
```
I see a PR (https://github.com/aws-amplify/amplify-js/pull/5372)  merged a few days ago, but it does not seem to fix the issue.

**Comment by Ashish-Nanda** [comment]
@ThatMate investigating the require cycles.

Regarding AsyncStorage migration to the community package we are working on the change. Will have a PR for that in the near future.

**Comment by AlexandruCalinica** [comment]
I'm having the same issues with aws-amplify@3.0.17 and aws-amplify-react-native@4.2.0. Fresh install of a react native project. Are these warnings going to affect my project in the longterm?

**Comment by Davidson-Mike** [comment]
Hello, I'm having the same issue as well with aws-amplify@3.0.18
The async storage warning I'm not too concerned about but the require cycles should be resolved right away.

**Comment by ThatMate** [comment]
Any updates?

**Comment by ankur-1989** [comment]
same issue +1

**Comment by arodri48** [comment]
I have been running into the same issue. I hope a fix for this is generated soon. Please keep us updated.

**Comment by kilisoria** [comment]
Hi Guys! same issue here. Anyone has some news? Thanks!

**Comment by Sacinandan** [comment]
Hello! Same issue.

I replaced the import for AsyncStorage in node_modules, but still has an issue with **Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle**:

`WARN     Require cycle: node_modules/@aws-amplify/pubsub/lib-esm/index.js -> node_modules/@aws-amplify/pubsub/lib-esm/PubSub.js -> node_modules/@aws-amplify/pubsub/lib-esm/Providers/index.js -> node_modules/@aws-amplify/pubsub/lib-esm/Providers/AWSAppSyncRealTimeProvider.js -> node_modules/@aws-amplify/pubsub/lib-esm/index.js

WARN     Require cycle: node_modules/@aws-amplify/datastore/lib-esm/util.js -> node_modules/@aws-amplify/datastore/lib-esm/types.js -> node_modules/@aws-amplify/datastore/lib-esm/util.js

WARN     Require cycle: node_modules/aws-amplify/lib-esm/index.js -> node_modules/aws-amplify/lib-esm/withSSRContext.js -> node_modules/aws-amplify/lib-esm/index.js`

**Comment by keisan1231** [comment]
same issue😓

**Comment by armando-fm** [comment]
Same issue here

**Comment by Naes0** [comment]
same issue

**Comment by itsmelion** [comment]
Well, these are two different problems, so keep a better track of progress and conversations i think should be 2 issues.

In my case, 
- i **still get** is deprecation warning of _AsyncStorage_ from react-native core.
- I **don't get** the _require cycle_ after i changed from using the main repo default exports (aka: `Amplify from 'aws-amplify'`) to granularly the ones i needed ex:
```javascript
import Auth from '@aws-amplify/auth';
import Amplify from '@aws-amplify/core';
```
obviously i stopped getting it, because it seems the cycles are in PubSub/Datastore/others..
so if you are not using these services, i recommend you to do this.

**Comment by ajnunez16** [comment]
same issue

**Comment by usama-asfar** [comment]
any fix?

**Comment by Junhano** [comment]
any update?

**Comment by giulio-dds** [comment]
Unfortunately I also have the same issue on my app (React Native w. Amplify). I don't know if it happens to the others as well, but after that, the application runs various instances of `BUNDLE ./index.js` until the app crashes (actually it's freezing my screen). 
After a rafresh everything is ok, anyway... is not so comfortable because it happens very often.

**Comment by usama-asfar** [comment]
I just go through the source code the issue is AsyncStorage had been imported from `react-native` but AsyncStorage had moved to a sperate dependency which managed by the react-native community [@react-native-community/async-storage](https://github.com/react-native-async-storage/async-storage) I don't get time to fix this and PR it.

**Comment by itsmelion** [comment]
No bot, the require cycles still need need to be dealt with.

**Comment by aquile** [comment]
Long story short: 
I've dealt with Async Storage warning by patching the @aws-amplify source.


Long story long  🙄:
After I've read this [comment](https://github.com/aws-amplify/amplify-js/pull/4027#issuecomment-628050861) and reviewed this [PR#4402](https://github.com/aws-amplify/amplify-js/pull/4402/commits/1207227cae5874d3f42599a6eecc5c05f3d6d86d) and because we don't use Expo I decided to not wait until amazon guys will push the fix.
Here is how I deal with
`Warning: Async Storage has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/async-storage' instead of 'react-native'. See https://github.com/react-native-community/react-native-async-storage` warning:

We use [patch-package](https://github.com/ds300/patch-package) in our RN project.
Here is the [usage](https://github.com/ds300/patch-package#usage) explanation. Which is can be shortened to:
Let's say we're using aws-amplify in our app. And you want to replace -import { AsyncStorage } from 'react-native'; with +import AsyncStorage from '@react-native-community/async-storage';.
1. Open file "package.json" and remove line 
   `"postinstall": "patch-package && ./scripts/whatever.sh"`
   from "scripts:" section and save the changes
2. Execute 
   `yarn clean`
   from root folder of the project
3. Make the desired changes to the source files and save them
4. Execute 
   `yarn patch-package @aws-amplify/core && yarn patch-package @aws-amplify/cache && yarn patch-package @aws-amplify/datastore`
   from root folder of the project, it compares a clean install to your modified dependency
5. Check new .patch file in patches directory and build the project to check does it help.
6. Revert changes from step 1 and commit your code.
7. Voila, you don't see ugly warning any more  😊

Step 3 in details:
- go `node_modules/@aws_amplify`
- find all lines with `import { AsyncStorage } from 'react-native'` in *.js & *.ts files
- replace it with `import AsyncStorage from '@react-native-community/async-storage'`
-  👌 perfecto!

Disclamer:
Also, I tried to add line `"@react-native-community/async-storage": "^1.6.2",` to the `"dependencies"` and `"devDependencies"` sections on `node_modules/@aws-amplify/core/package.json`, but I didn't see that in .patch file nor in package.json after applying the patch (which is expectable  🙈).
However, I believe you already has `@react-native-community/async-storage` in your package.json, so it should work.

**Comment by tomergafner** [comment]
+1 Same issue

**Comment by zarincheg** [comment]
Same issue.

**Comment by sotomaque** [comment]
same issue

**Comment by ghadeeraqraa1992** [comment]
same issue

**Comment by ghadeeraqraa1992** [comment]
same issue

**Comment by yspektor** [comment]
+1 same issue

**Comment by ws333** [comment]
+1

**Comment by bmoby** [comment]
+1 same

**Comment by lucaasdsm** [comment]
+1 same

**Comment by gvankeerberghen** [comment]
+1 same

**Comment by jonnyn** [comment]
+1 same issue

**Comment by sammartinez** [comment]
All, 

I wanted to provide an update here. We are going to be migrating to the Community version of Async Storage in the coming weeks. This will be a breaking change and a major version bump for us, so we are working on the logistics of this prior to getting it out to you folks. Just wanted to state, we hear you and will provide more of an update once we have something.

Thanks! 
Sam

**Comment by sotomaque** [comment]
Thanks for the update!

**Comment by Ashish-Nanda** [comment]
Hi All,
The PR #8250 to migrate to the community version of AsyncStorage has just been merged to `main`
You will be able to test the changes on the @unstable tag later today. We'll update this thread as soon as its available.

We plan to release the this change in our next major version tomorrow.

**Comment by Ashish-Nanda** [comment]
Hi All,
We released `aws-amplify@4.0.0` that uses the community version of AsyncStorage `@react-native-async-storage/async-storage`

Please take a look at the installation and setup instructions [here ](https://github.com/aws-amplify/amplify-js#amplify-4xx-has-breaking-changes-for-react-native-please-see-the-breaking-changes-below)

Closing out this issue now since the fix has been released.

**Comment by plus-** [comment]
I believe this does not fix the require cycles issue posted initially (there were 2 issues reported together originally)

I've tested with 4.0.3 and still get the following:

> 
>  WARN  Require cycle: ../../node_modules/@aws-amplify/pubsub/lib-esm/index.js -> ../../node_modules/@aws-amplify/pubsub/lib-esm/PubSub.js -> ../../node_modules/@aws-amplify/pubsub/lib-esm/Providers/index.js -> ../../node_modules/@aws-amplify/pubsub/lib-esm/Providers/AWSAppSyncRealTimeProvider.js -> ../../node_modules/@aws-amplify/pubsub/lib-esm/index.js
> 
> Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
>  WARN  Require cycle: ../../node_modules/@aws-amplify/datastore/lib-esm/types.js -> ../../node_modules/@aws-amplify/datastore/lib-esm/util.js -> ../../node_modules/@aws-amplify/datastore/lib-esm/types.js
> 
> Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
>  WARN  Require cycle: ../../node_modules/aws-amplify/lib-esm/index.js -> ../../node_modules/aws-amplify/lib-esm/withSSRContext.js -> ../../node_modules/aws-amplify/lib-esm/index.js
> 
> Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

**Comment by thomasyim02** [comment]
> I believe this does not fix the require cycles issue posted initially (there were 2 issues reported together originally)
> 
> I've tested with 4.0.3 and still get the following:
> 
> > WARN  Require cycle: ../../node_modules/@aws-amplify/pubsub/lib-esm/index.js -> ../../node_modules/@aws-amplify/pubsub/lib-esm/PubSub.js -> ../../node_modules/@aws-amplify/pubsub/lib-esm/Providers/index.js -> ../../node_modules/@aws-amplify/pubsub/lib-esm/Providers/AWSAppSyncRealTimeProvider.js -> ../../node_modules/@aws-amplify/pubsub/lib-esm/index.js
> > Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
> > WARN  Require cycle: ../../node_modules/@aws-amplify/datastore/lib-esm/types.js -> ../../node_modules/@aws-amplify/datastore/lib-esm/util.js -> ../../node_modules/@aws-amplify/datastore/lib-esm/types.js
> > Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
> > WARN  Require cycle: ../../node_modules/aws-amplify/lib-esm/index.js -> ../../node_modules/aws-amplify/lib-esm/withSSRContext.js -> ../../node_modules/aws-amplify/lib-esm/index.js
> > Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

+1 Same here.... Require Cycle issue has not been fixed! Please reopen the issue.

**Comment by sammartinez** [comment]
@plus- and @thomasyim02 I created an issue for what you are calling out for [Require Cycles](https://github.com/aws-amplify/amplify-js/issues/8421). Can you please place any examples (similar to your code snippets above) in the new issue? Thanks ahead of time!

**Comment by themse** [comment]
```
aws-amplify : 4.1.0
@react-native-async-storage/async-storage: 1.15.5
```
Require Cycles still exist

**Comment by sammartinez** [comment]
Thanks for this feedback @themse I created a [separate issue](https://github.com/aws-amplify/amplify-js/issues/8421) for this above. Can you please add your data to this [issue](https://github.com/aws-amplify/amplify-js/issues/8421)?

**Comment by kartikeyvaish** [comment]
```
"react-native": "0.64.3",
"aws-amplify": "^4.3.18",
"@react-native-async-storage/async-storage": "^1.17.3",
```

Require Cycles still exist

**Comment by joseasanchezzz91** [comment]
same issue

"aws-amplify": "4.2.11",
"react": "17.0.2",
 "react-native": "^0.66.5",
  "@react-native-async-storage/async-storage": "^1.15.8",
 
 Require Cycles still exist

**Comment by ParkAward** [comment]
same issue +1

"aws-amplify": "5.0.1",
"react": "17.0.2",
"react-native": "^0.65.3",
"@react-native-async-storage/async-storage": "^1.15.14",
