### ISSUE TITLE
Sign in event gets registered multiple times when using regular Auth.signIn()

### ISSUE THREAD

**Issue by ooridoori** [aws-amplify/amplify-js#6069]
**Describe the bug**
When a user signs in using Auth.signIn() the "signIn" event is registered multiple times in the Hub listener

**To Reproduce**
1. Add a log inside the "signIn" event in the Hub.listener callback
2. Open devtools
3. Sign in using Auth.signIn()
4. Notice there is at least 4 or more logs and the same amount of network calls 

**Expected behavior**
The sign in event should only happen once - im bypassing this by keeping track of page loads. :\

**Code Snippet**
```
Hub.listen('auth', ({ payload: { event, data } }) => {
    switch (event) {
      case 'signIn':
         console.log('heard sign in event! ')
//...rest of code
```

**Screenshots**
![Screen Shot 2020-06-11 at 6 14 01 PM](https://user-images.githubusercontent.com/8499727/84454771-627c7800-ac10-11ea-8edb-94fc0b2df38a.png)
![Screen Shot 2020-06-11 at 6 22 42 PM](https://user-images.githubusercontent.com/8499727/84454854-8e97f900-ac10-11ea-9668-968aaa63da40.png)

**Comment by danluszcz-pariveda** [comment]
I'm seeing a possibly related issue, our Cognito Pre Token Generation lambda function was triggered 82 times in less than a second for the same user.

**Comment by ehtulhaq** [comment]
I see this issue too..specially on android when using social federated sign up

**Comment by ehtulhaq** [comment]
Since i had business logic that was being called many times my workaround was to move the business logic out from Hub.listen and add another middle layer where my business logic gets executed. Sign in event in Hub.listen would redirect the user to the middle layer where my business logic gets executed and which then redirects to the appropriate screen.

**Comment by nqbao** [comment]
I also have the same problem. The sign event is called multiple time when login

<img width="182" alt="Screen Shot 2020-10-07 at 3 13 25 PM" src="https://user-images.githubusercontent.com/177742/95393557-ac6c2680-08af-11eb-9bdf-bf97a33c5f85.png">

The code is quite simple

```
    Hub.listen("auth", ({ payload: { event, data } }) => {
      console.log('event', event)
      switch (event) {
        case "signIn":
          // console.log(123)
          this.setState({ user: data });
          break;
        case "signOut":
          this.setState({ user: null });
          break;
        case "customOAuthState":
          this.setState({ customState: data });
      }
    });
```

**Comment by ericclemmons** [comment]
Closing, as https://github.com/aws-amplify/amplify-js/pull/7718 (via `v1.0.1`) should resolve this duplication issue.

To install the latest version of `@aws-amplify/ui-react`, for example:
```shell
npm install aws-amplify @aws-amplify/ui-react
# or
yarn add aws-amplify @aws-amplify/ui-react
```

**Be sure to install `aws-amplify`**, rather than `@aws-amplify/core` directly. 
(`aws-amplify` will install `@aws-amplify/core` and other dependencies itself)

**However, if you're not using any of the UI components and still experiencing this issue, please let us know!** 🙏

**Comment by colemars** [comment]
If you're not using the ui components and seeing this issue make sure you're only initializing your listener once..

**Comment by aloverso** [comment]
I am using `"@aws-amplify/ui-react": "^1.0.3",` and still seeing this issue: my `handleAuthStateChange` callback from the `<AmplifyAuthenticator/>` UI component is getting triggered with the signedin event several (6-10) times when a signin occurs

**Comment by JosephVasse** [comment]
Hello, as @colemars i am not using any UI components but I got the Signin (via FederatedSignin) and the SignOut Event triggered multiples times when doing Auth stuff
