### ISSUE TITLE
DataStore cannot delete `hasOne` relationships

### ISSUE THREAD

**Issue by abdielou** [aws-amplify/amplify-js#6560]
**Describe the bug**
DataStore cannot delete `hasOne` relationships. It breaks at `IndexedDBAdapter.deleteTraverse` when trying to find the `recordToDelete` of the `HAS_ONE` relationType.

```console
Unhandled Runtime Error
NotFoundError: Failed to execute 'index' on 'IDBObjectStore': The specified index was not found.
```

**To Reproduce**
1. Init Amplify. Add GQL API. Enable DataStore.
2. Define the Schema below 👇 
3. Generate Models. Push API.
4. Create `Team` then create `Project` with `teamID`.
5. Delete `Project`.
6. ERROR

**Expected behavior**
The DataStore should correctly traverse the `hasOne` relationship to delete the `Team` record before deleting the `Project` record.

**Code Snippet**

### Schema
```graphql
type Project @model {
  id: ID!
  name: String
  teamID: ID!
  team: Team @connection(fields: ["teamID"])
}

type Team @model {
  id: ID!
  name: String!
}
```
### Create `Team` then create `Project` with `teamID`.
```javascript
    DataStore.save(
      new Team({ name: 'Team Name' })
    )
    .then(async ({ id: teamID }) => {
      DataStore.save(
        new Project({ teamID })
      )
    })
```
### Delete `Project`.
```javascript
DataStore.delete(Project, project.id)
```

**What is Configured?**
Amplify 4.27.1
Simple Auth with Cognito
GraphQL / Dynamo API
DataStore
NextJS app (irrelevant)

**Additional context**
A couple of notes.

- From the implementation, looks like an index is expected for the `hasOne` relationship. 
https://github.com/aws-amplify/amplify-js/blob/main/packages/datastore/src/storage/adapter/indexeddb.ts#L676-L682
```typescript
  case 'HAS_ONE':
    for await (const model of models) {
      const recordToDelete = <T>await this.db
        .transaction(storeName, 'readwrite')
        .objectStore(storeName)
        .index(index) // <-- 🤔
        .get(model.id);
```
- This goes counter to the docs where it states:
>https://docs.amplify.aws/cli/graphql-transformer/directives#has-one
>A Has One `@connection` can only reference the primary index of a model (ie. it cannot specify a “keyName” as described below in the Has Many section).
- This is also where the error occurs, as `index` is `undefined`.

**Comment by abdielou** [comment]
Here's a sample project to make it easier to reproduce.

https://github.com/abdielou/nextjs-amplify-hasone-bug

**Comment by abdielou** [comment]
Here's also something that's a bit confusing. The generated schema (`src/models/schema.js`) seems not to be properly generated.

The GQL schema definition looks like this:

```graphql
type Project @model {
  # ...
  teamID: ID!
  team: Team @connection(fields: ["teamID"])
}
# ...
```

And this is the generated DataStore schema.

```javascript
export const schema = {
  "models": {
    "Project": {
      // ...
      "fields": {
        // ...
        "team": {
          // ...
          "association": {
            "connectionType": "HAS_ONE",
            "associatedWith": "id"
          }
        }
      },
      // ...
    },
    // ...
  },
  //...
};
```

My question is, why isn't the association including the `targetName` as it was defined (`teamID`)? This would be a problem when trying to look up the correct ID for the team relationship in `deleteTraverse`. Actually, when you debug the code, you see that it's specifying the `Project.id` but using the `Team` model. So, even if we specify the correct index (`byId`), the `Team.id` would not be used.

**Comment by abdielou** [comment]
@manueliglesias Tagging you here as it seems you implemented the bulk of this code.

I can happily help with a PR but I would need some direction as I am still not fully familiar with the underlying algorithm and architecture you guys have implemented in the DataStore.

**NOTE:** I understand `hasOne` relationships might be smelly when used with DynamoDB, but my specific use-case requires a `hasOne` relationship with a `@model`. This is my use-case for reference. https://github.com/aws-amplify/amplify-cli/issues/4794#issuecomment-665420716

**Comment by TheMoums** [comment]
Ran into the same issue.

Any news on this @mahayash315 ?

**Comment by mauerbac** [comment]
Hey @TheMoums - just spoke to the team. Not current ETA, but pushing the team to take a look.

**Comment by iartemiev** [comment]
@abdielou I was able to reproduce the issue. There are 2 sides to it, as you suggested. One is in the library (trying to access a nonexistent index) and also a bug in the CLI where `codegen models` is incorrectly setting the `associatedWith` field.

I'll open an issue in the CLI repo and reference this. I've written a bug fix for the library side already, so once the codegen bug fix gets merged, I'll open a PR for the library bug fix as well.

**Comment by AaronZyLee** [comment]
@abdielou @iartemiev I think it is not the modelgen bug but the [amplify doc](https://docs.amplify.aws/cli/graphql-transformer/directives#has-one) that misleads the understanding of the `HAS_ONE` relationship. Suppose from your case that 
#### _Project_ `HAS_ONE` _Team_. 
Before writing the schema I attach this [post](https://stackoverflow.com/questions/3808926/whats-the-difference-between-belongs-to-and-has-one) about the difference between `HAS_ONE` and `BELONGS_TO` FYI, which is not clarified in the original docs. The main difference is:

> To determine who "has" the other object, look at where the foreign key is. We can say that a `User` "has" a `Profile` because the profiles table has a `user_id` column.

Based on the conclusion, it is obvious that it is not a good idea to add `teamID` in `Project` but to add `projectID` in `Team`. The following is the alternative schema and it works for me on datastore deleting.
### Schema
```
type Project @model {
  id: ID!
  name: String!
  team: Team @connection(fields: ["id"])
}

type Team @model 
  @key(fields: ["projectID"]) {
  id: ID!
  name: String
  projectID: ID!
}
```
### Output for `schema.js`
```
"Project": {
  "name": "Project",
  "fields": {
      // ...
      "team": {
          "name": "team",
          "isArray": false,
          "type": {
              "model": "Team"
          },
          "isRequired": false,
          "attributes": [],
          "association": {
              "connectionType": "HAS_ONE",
              "associatedWith": "projectID"
          }
      }
  },
},
```

**Comment by iartemiev** [comment]
@AaronZyLee the Stack Overflow answer you're linking to is discussing this from an RDB design perspective. That's not necessarily relevant here, since we're dealing with NoSQL and GraphQL where different normalization rules and access patterns apply.
Even though your suggested schema might work, I think it's needlessly complex for a simple Has One relationship. Using `@key` will create a GSI on the Team table, which adds cost, but doesn't add value. I think what we currently have in the docs makes more sense for this use case. Feel free to reach out to me internally and we can discuss this in more detail.

**Comment by matansagee** [comment]
@abdielou Hi! When you are using the same schema you wrote in the first comment, are you able to get the **Team** object back when querying **Project**?

`type Project @model {
  id: ID!
  name: String
  teamID: ID!
  team: Team @connection(fields: ["teamID"])
}

type Team @model {
  id: ID!
  name: String!
}`

**Comment by dlenington** [comment]
Any updates on this issue?

**Comment by iDavidB** [comment]
Any updates on this? Still having this same issue.

**Comment by ajayGadhiya** [comment]
I try to delete data with a simple datastore delete query but it throws the below log in console.
![image](https://user-images.githubusercontent.com/70691615/116854577-84f6f580-ac15-11eb-9b56-65b7e45a4366.png)

It is my code...

```
export declare class Department {
  readonly id: string;
  readonly departmentCode?: string;
  readonly phone?: string;
  readonly name?: string;
  readonly description?: string;
  readonly buildingID: string;
  readonly building?: Building;
  readonly floor?: string;
  readonly wing?: string;
  readonly searchField?: string;
  constructor(init: ModelInit<Department>);
  static copyOf(source: Department, mutator: (draft: MutableModel<Department>) => MutableModel<Department> | void): Department;
}

export function deleteDepartments(id) {
  return DataStore.delete(Department, id)
    .catch(console.log)
}
```

**Comment by iartemiev** [comment]
We've released a fix for this issue in aws-amplify@3.4.0. 

For existing projects, you may need to set [this](https://docs.amplify.aws/cli/reference/feature-flags#codegen) CLI feature flag to `true` in `./amplify/cli.json`. Afterward, make sure you have the latest version of @aws-amplify/cli, and run `amplify codegen models`. 

If the model is getting generated correctly, you will see a new `targetName` property in the schema.js containing the field you've specified in `@connection`. 

For example:

For this schema.graphql
```gql
type Project @model {
  id: ID!
  name: String
  teamID: ID!
  team: Team @connection(fields: ["teamID"])
}

type Team @model {
  id: ID!
  name: String!
}
```

You should see the following in `/models/schema.js` after you run `amplify codegen models`:

```js
export const schema = {
  "models": {
    "Project": {
      "name": "Project",
        "fields": {
          ...,
          "teamID": {
            "name": "teamID",
            "isArray": false,
            "type": "ID",
            "isRequired": true,
            "attributes": []
          },
          "team": {
            "name": "team",
            "isArray": false,
            "type": {
              "model": "Team"
            },
            "isRequired": false,
            "attributes": [],
            "association": {
              "connectionType": "HAS_ONE",
              "associatedWith": "id",
              "targetName": "teamID" <----
            }
          }
          ...,
```

**Comment by waqasmalik10** [comment]
@iartemiev  still showing the same error on deleting Project. after I run  amplify codegen models. schema.js file matches with with your specified schema. but error still remains.

![Screenshot from 2021-06-07 16-27-41](https://user-images.githubusercontent.com/20343290/121009354-7f10a900-c7ad-11eb-8aff-691317e6b90c.png)

**Comment by iartemiev** [comment]
@waqasmalik10 do you have [this feature flag](https://docs.amplify.aws/cli/reference/feature-flags#useAppsyncModelgenPlugin) enabled?

**Comment by waqasmalik10** [comment]
This is my cli.json file in the project’s amplify folder. please let me know if I am doing anything wrong.
using.
 amplify-cli 4.52.0
 aws-amplify 4.0.3
 
`{
    "features": {
    "graphqltransformer": {
        "addmissingownerfields": true,
        "validatetypenamereservedwords": true,
        "useexperimentalpipelinedtransformer": false,
        "enableiterativegsiupdates": true,
        "secondarykeyasgsi": true,
        "skipoverridemutationinputtypes": true
    },
    "frontend-ios": {
        "enablexcodeintegration": true
    },
    "auth": {
        "enablecaseinsensitivity": true,
        "useinclusiveterminology": true,
        "breakcirculardependency": true
    },
    "codegen": {
        "useAppsyncModelgenPlugin": true,
        "useappsyncmodelgenplugin": true,
        "usedocsgeneratorplugin": true,
        "usetypesgeneratorplugin": true,
        "cleangeneratedmodelsdirectory": true,
        "retaincasestyle": true,
        "addtimestampfields": true,
        "handlelistnullabilitytransparently": true
    },
    "appsync": {
        "generategraphqlpermissions": true
    }
    }
}`

**Comment by iartemiev** [comment]
@waqasmalik10, could you run `npx envinfo --system --binaries --browsers --npmPackages --duplicates --npmGlobalPackages` from the root of your project and paste the output here?

**Comment by waqasmalik10** [comment]
System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
    Memory: 6.02 GB / 15.06 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Browsers:
    Chrome: 90.0.4430.72
    Firefox: 89.0
  npmPackages:
    @aws-amplify/core: ^2.2.5 => 2.3.0 (4.0.3)
    @aws-amplify/datastore: ^1.0.8 => 1.2.0 (3.0.3)
    @babel/plugin-transform-runtime: ^7.14.3 => 7.14.3 
    @babel/preset-env: ^7.14.2 => 7.14.4 
    aws-amplify: 4.0.3 => 4.0.3 
    aws-appsync: ^4.0.3 => 4.0.3 
    axios: ^0.21.1 => 0.21.1 (0.19.2)
    babel-jest: ^27.0.1 => 27.0.2 
    global-configuration: ^0.3.1 => 0.3.1 
    ini: ^1.3.5 => 1.3.8 
    inquirer: ^6.5.1 => 6.5.2 
    jest: ^27.0.1 => 27.0.4 
    ts-jest: ^27.0.1 => 27.0.2 
  npmGlobalPackages:
    @aws-amplify/cli: 4.52.0
    @trades-org/trades.org-abstraction-library: 1.0.3
    npm: 6.14.11

**Comment by iartemiev** [comment]
Looks like you have older versions of `@aws-amplify/core` and `@aws-amplify/datastore` packages installed alongside the latest `aws-amplify`. Having the scoped packages installed explicitly can cause issues and conflicts.

Try the following steps:

1. `npm uninstall @aws-amplify/core @aws-amplify/datastore`
2. `rm -rf node_modules package-lock.json`
3. `npm i`

**Comment by waqasmalik10** [comment]
Thank you @iartemiev for your timely response! Issue has been resolved
