### ISSUE TITLE
AmplifyAuthenticator - Verify Contact Information Screen displays "your.adress@example.com"

### ISSUE THREAD

**Issue by liamaws** [aws-amplify/amplify-js#6710]
**Describe the bug**
After federated sign in, the verify contact information screen displays "your.adress@example.com" as the email address for verification

**To Reproduce**

1. Go to https://master.dw8p5s05jola3.amplifyapp.com/
2. Sign in using an external IdP (Google for example)
3. You will see an "Account recovery requires verified contact information" screen (screenshot below)

**Expected behavior**
This screen did not previously show up after federated sign in, so I am not sure the exact expected behavior. I found this issue https://github.com/aws-amplify/amplify-js/issues/6481 and this PR https://github.com/aws-amplify/amplify-js/pull/6508, so looks like this is verification screen is intended. However I think either "Email" or the users actual email address should show up as the option to select.

**Code Snippet**
Full code is [here](https://github.com/awslabs/aws-amplify-identity-broker) for those who have access
```
  <AmplifyAuthenticator usernameAlias="email" style={{ textAlign: 'center' }}>
            <AmplifyForgotPassword
              usernameAlias="email"
              slot="forgot-password"
              formFields={[
                {
                  type: "email",
                  required: true,
                },
              ]}></AmplifyForgotPassword>
            <AmplifySignIn
              usernameAlias="email"
              slot="sign-in"
              formFields={[
                {
                  type: "email",
                  required: true,
                },
                {
                  type: "password",
                  required: true,
                }
              ]}></AmplifySignIn>
            <AmplifySignUp
              usernameAlias="email"
              slot="sign-up"
              formFields={[
                {
                  type: "email",
                  required: true,
                },
                {
                  type: "password",
                  required: true,
                },
                {
                  type: "phone_number",
                  required: false,
                },
                {
                  type: "locale",
                  value: this.state.lang,
                  inputProps: {
                    type: 'hidden',
                  }
                }
              ]}></AmplifySignUp>
            <div>
              {I18n.get("WAIT_REDIRECTION")}
              <AmplifySignOut />
            </div>
          </AmplifyAuthenticator>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/67014943/92030857-a5dd1300-ed35-11ea-979a-305ee2ed2d13.png)

<details>
  <summary><strong>Environment</strong></summary>

```
  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 59.58 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.0 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Firefox: 68.8.0
    Safari: 13.1.2
  npmPackages:
    @aws-amplify/ui-react: ^0.2.15 => 0.2.15 
    @testing-library/jest-dom: ^5.11.4 => 5.11.4 
    @testing-library/react: ^10.4.9 => 10.4.9 
    @testing-library/user-event: ^12.1.3 => 12.1.3 
    aws-amplify: ^3.0.24 => 3.0.24 
    axios: ^0.20.0 => 0.20.0 
    jwt-decode: ^2.2.0 => 2.2.0 
    react: ^16.13.1 => 16.13.1 
    react-app-rewired: ^2.1.6 => 2.1.6 
    react-dom: ^16.13.1 => 16.13.1 
    react-router-dom: ^5.2.0 => 5.2.0 
    react-scripts: 3.4.3 => 3.4.3 
  npmGlobalPackages:
    @aws-amplify/cli: 4.28.1
    ask-cli: 2.13.0
    nodemon: 2.0.4
    npm: 6.14.8
    serve: 11.3.2
    serverless: 1.73.1

```

</details>

**Comment by jordanranz** [comment]
Hey @liamaws, unfortunately I don't have access to that repo but It seems it is you are using `Translations` to customize the `SIGN_UP_EMAIL_PLACEHOLDER` or `VERIFY_CONTACT_EMAIL_LABEL` and that might cause a conflict for retrieving the correct value here. Can you find `your.adress@example.com` in your codebase and share the code with me?

**Comment by liamaws** [comment]
Oh good catch. I searched `your.adress@example.com` in the amplify-js repo and couldn't find where it was coming from but I didn't think to look in my own code. :man_facepalming:

I will pm you the code.

**Comment by jordanranz** [comment]
After speaking offline, we determined that this was a translation assignment in your application. Going to close this particular issue as the originally described issue is solved.

**Comment by xavierraffin** [comment]
After discussion with Jordan, we decided to re-open because the underlying issue is not solved.

To me the issue is that using `Auth.federatedSignIn` the AuthState the UI get in return is always **verifyContact**.
I assume it is due to the fact that for all external IdP Cognito mark the `email_verified` as **false** and Amplify use that to decide what state to go on.

This does not make sense. Since the identity is managed by a trusted IdP we have no valid reason to ask for email confirmation.
So, Amplify Auth should instead look at the `Account Status` and not go for **verifyContact** if the value is `Enabled / EXTERNAL_PROVIDER`

**Comment by ericclemmons** [comment]
Confirmed that this behavior exists and is undesirable.

1. Clicking "Sign in with Google"

	> ![Screen Shot 2020-11-24 at 2 28 30 PM](https://user-images.githubusercontent.com/15182/100158645-5b18f600-2e61-11eb-8392-b9fecb7c4399.png)

1. After the redirect, I'm prompted to verify my email:

	> ![Screen Shot 2020-11-24 at 2 28 12 PM](https://user-images.githubusercontent.com/15182/100158677-6835e500-2e61-11eb-82a4-f2bb50635385.png)

1. However, when refreshing the page, I get the desired experience:

	> ![Screen Shot 2020-11-24 at 2 28 20 PM](https://user-images.githubusercontent.com/15182/100158697-7421a700-2e61-11eb-96c8-23dc4b5545a8.png)

**Comment by shivanshsinghraghuvanshi** [comment]
Guys what the status on this issue. I am facing same issue while connecting Cognito with my custom IDP(Keycloack)

**Comment by aangeles2807** [comment]
Summarizing the problem: When adding the federal entity of Apple Id, the Verify contact screen always appears every time you login even though the email is already verified.

The problem occurs because in the mapping of the attributes in Apple there is no email_verified field, therefore every time it is consulted in amplify's login it asks for it to be verified.

If you try removing the email_verified mapping in google, the Verify Contact screen will always appear as well.

The solution to this problem is to create a lambda function that adds the attribute automatically and configure it in the userpool triggers called “Post authentication” and “Post confirm”.

This [publication](https://saachitech.medium.com/react-native-social-sign-in-with-apple-and-amplify-6c803b2971d6) explains the solution to this problem in a complete way.

**Comment by eddiekeller** [comment]
Commenting here again that this is still an issue. I was able to reproduce it this morning. I will be taking a deeper look at it.

I noticed that I did get an error back from OAuth after logging in with Google. I'm guessing that this error is being caught and so even though the login through Google was successful, it isn't hitting our piece of code that would correctly change the auth state to recognize the user as already being verified.

**Comment by eddiekeller** [comment]
Just a small update - I haven't found a super reliable fix for this yet. This will require a bit further investigation from our side.
