### ISSUE TITLE
[aws-amplify-react-native] Update to @react-native-community/picker

### ISSUE THREAD

**Issue by dannyoo** [aws-amplify/amplify-js#6845]
**Describe the bug**
In aws-react-native, there is still Picker usage which is depreciated. As stated by the [rn doc](https://reactnative.dev/docs/picker), it should use [@react-native-community/picker](https://github.com/react-native-community/react-native-picker) instead.

**Comment by pratyaksh123** [comment]
Hey, I would like to work on this @dannyoo

**Comment by HunainHumail** [comment]
Hey! I will upgrade your Picker to @react-native-community/picker. Please assign me this issue

**Comment by jeremygustine** [comment]
Is there any movement on this issue?  It looks like `amplify-react-native/src/AmplifyUI.tsx` still has the offending code in place.  There was a PR some time ago that appeared to fix the issue (https://github.com/aws-amplify/amplify-js/pull/6871), but it looks like it was closed without being merged.  Any updates?

**Comment by jeremygustine** [comment]
BTW, I'm happy to submit a new PR for this, just want to make sure there isn't any duplicate effort in progress.

**Comment by TheDicko** [comment]
Any update on this? I have literally no way to create my react native app with amplify

**Comment by pratyaksh123** [comment]
> @pratyaksh123 Why was your PR closed?

No idea why it wasn't reviewed.

**Comment by emreedgu** [comment]
I made a patch . I hope that makes it easier 😃

1. get the modified AmplifyUI.js from this gist (for convenience) https://gist.github.com/emreedgu/0194b25ffa5376b0ba16adb8bb636094 .  And name it as AmplifyUI.js
2. replace the faulty file with modified one at node_modules/aws-amplify-react-native/dist/

**Comment by kirkryan** [comment]
@renebrandel - could we have some visibility on this please?

Kirk
AWS Community Builder

**Comment by calebpollman** [comment]
Have merged a fix available for testing under the `unstable` tag:
- yarn: `yarn @react-native-picker/picker aws-amplify aws-amplify-react-native@5.0.6-unstable.14`
- npm: `npm install @react-native-picker/picker aws-amplify aws-amplify-react-native@5.0.6-unstable.14`
- expo: `expo install @react-native-picker/picker aws-amplify aws-amplify-react-native@5.0.6-unstable.14`

**Comment by flogy** [comment]
`aws-amplify-react-native@5.0.6-unstable.14` works for me with `0.66.2`

**Comment by kirkryan** [comment]
I'll test in my latest RN project later tonight and report back my findings. 🤟

**Comment by josuemy** [comment]
@floggy what steps did you take to make it work? It doesn't work for me with RN 0.66.2

**Comment by kirkryan** [comment]
I can confirm this has fixed the issue on RN 0.66.1

I simply ran npm install @react-native-picker/picker aws-amplify aws-amplify-react-native@5.0.6-unstable.14 and then a pod update (with repo update), rebuilt the project in Xcode and voila - working.

**Comment by flogy** [comment]
> @flogy what steps did you take to make it work? It doesn't work for me with RN 0.66.2

Same as described by @kirkryan above 👍

**Comment by calebpollman** [comment]
Fix has been released in `aws-amplify-react-native@6.0.1`

**Comment by guibovo** [comment]
@calebpollman I have just created a new project using aws-amplify-react-native@6.0.1 and I still get this error

**Comment by calebpollman** [comment]
@guibovo 👋 That is expected and is documented in our [README](https://github.com/aws-amplify/amplify-js#amplify-4xx-has-breaking-changes-for-react-native-please-see-the-breaking-changes-below).

**Comment by arnoldc** [comment]
its working for me (RN 0.66.3)

yes just install the `@react-native-picker/picker` and it should work already
please note in ios, it needs to do a `pod install` in the ios directory in order to take effect the changes
(there is a guide installation at repo of picker - https://github.com/react-native-picker/picker)
