### ISSUE TITLE
Previously deleted items are being returned as part of a query after going from offline -> online network state

### ISSUE THREAD

**Issue by sconway** [aws-amplify/amplify-js#8158]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

DataStore

### Amplify Categories

storage

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

We are currently using Datastore to manage overrides to an itinerary displayed in our app. We model an Override as

```
type Override @model {
    id: ID!
    createdBy: String
    date: String
    dayOfDuration: Int
    description: String
    isCreatedItem: Boolean
    isTdOnly: Boolean
    prodComponentId: ID!
    prodTourId: Int
    startTime: String
    title: String
    uniqueComponentId: ID!
}
```

Overrides can be created and deleted, but there is never more than 1 override created for a corresponding itinerary item. 

Adding and removing Datastore items in our application works as expected while a device is online, however the following scenario is giving us unexpected results:

1. Device saves an override via Datastore
2. Device deletes the override that was created in step 1
3. Device goes offline
4. Device saves a new override via Datastore
5. Device goes online
6. Device queries datastore for overrides and both the created override from step 4, and the deleted override from step 2 are returned

Example:
```
[ 
    { 
        id: '5a53e76f-9f2c-4492-9ee2-facf58626f8b',
        createdBy: null,
        date: '',
        dayOfDuration: 1,
        description: null,
        isCreatedItem: null,
        isTdOnly: true,
        prodComponentId: '16965791',
        prodTourId: 221398,
        startTime: null,
        title: '@@TEST3 -- offline Overnight Security',
        uniqueComponentId: '16965791-1',
        _version: 1,
        _lastChangedAt: 1619116075244,
        _deleted: null 
    },
    { 
        id: '2e7efb8e-2627-405c-b335-0df486b876f0',
        createdBy: null,
        date: '',
        dayOfDuration: 1,
        description: null,
        isCreatedItem: null,
        isTdOnly: true,
        prodComponentId: '16965786',
        prodTourId: 221398,
        startTime: null,
        title: 'Tour Director offline',
        uniqueComponentId: '16965786-1',
        _version: 1,
        _lastChangedAt: 1619120035725,
        _deleted: null 
    },
    { 
        id: 'a5dc883a-7b07-442f-8652-cec197966b53',
        createdBy: null,
        date: '',
        dayOfDuration: 1,
        description: null,
        isCreatedItem: null,
        isTdOnly: true,
        prodComponentId: '16965786',
        prodTourId: 221398,
        startTime: null,
        title: 'Tour Director edit 1',
        uniqueComponentId: '16965786-1',
        _version: 1,
        _lastChangedAt: 1619119769638,
        _deleted: null 
    }
]
```

In this example, the query was done after the device came back online. The last override in the example with title 'Tour Director edit 1' was deleted previously, and the second to last override with title 'Tour Director offline' was saved while the device was offline.

It's worth mentioning that everything appears as expected on the AppSync/Dynamo DB side of things. It is just the client-side device that is showing the bad data.

### Expected behavior

I would expect any Datastore item (override in our case) to be removed completely and not returned in future queries. I would expect the previous query to display:

```
[ 
    { 
        id: '5a53e76f-9f2c-4492-9ee2-facf58626f8b',
        createdBy: null,
        date: '',
        dayOfDuration: 1,
        description: null,
        isCreatedItem: null,
        isTdOnly: true,
        prodComponentId: '16965791',
        prodTourId: 221398,
        startTime: null,
        title: '@@TEST3 -- offline Overnight Security',
        uniqueComponentId: '16965791-1',
        _version: 1,
        _lastChangedAt: 1619116075244,
        _deleted: null 
    },
    { 
        id: '2e7efb8e-2627-405c-b335-0df486b876f0',
        createdBy: null,
        date: '',
        dayOfDuration: 1,
        description: null,
        isCreatedItem: null,
        isTdOnly: true,
        prodComponentId: '16965786',
        prodTourId: 221398,
        startTime: null,
        title: 'Tour Director offline',
        uniqueComponentId: '16965786-1',
        _version: 1,
        _lastChangedAt: 1619120035725,
        _deleted: null 
    }
]
```

without the deleted item.

### Reproduction steps

1. Device saves an override via Datastore
2. Device deletes the override that was created in step 1
3. Device goes offline
4. Device saves a new override via Datastore
5. Device goes online
6. Device queries datastore for overrides and both the created override from step 4, and the deleted override from step 2 are returned

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

We are using the latest version (`3.3.27`) of amplify

**Comment by iartemiev** [comment]
Hi @sconway, thanks for opening the issue. A couple of follow up questions:
* Are you using Expo or RN CLI? Mainly asking so that I can attempt to reproduce in the same env. 
* Please run `npx envinfo --system --binaries --browsers --npmPackages --duplicates --npmGlobalPackages` and copy-paste the output here
* Are you able to repro in Simulator? Or only on physical devices?
* Have you been experiencing this issue in previous versions of aws-amplify? Or only after upgrading to 3.3.27?
* Could you try using **aws-amplify@3.3.14** and letting us know if you're still running into the same issue?

**Comment by sconway** [comment]
> Hi @sconway, thanks for opening the issue. A couple of follow up questions:
> 
> * Are you using Expo or RN CLI? Mainly asking so that I can attempt to reproduce in the same env.
RN CLI

> * Please run `npx envinfo --system --binaries --browsers --npmPackages --duplicates --npmGlobalPackages` and copy-paste the output here

`
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 64.21 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 82.0.2
    Safari: 14.0.3
  npmPackages:
    @babel/core: ^7.6.2 => 7.12.3 
    @babel/runtime: ^7.6.2 => 7.12.5 
    @eftours/change-detection-graphql: ^1.0.1 => 1.0.1 
    @eftours/live-itinerary-factory: 2.3.1-rc.0 => 2.3.1-rc.0 (2.0.7-alpha.0)
    @jumpn/react-native-jetifier: ^0.1.4 => 0.1.4 
    @react-native-community/async-storage: ^1.11.0 => 1.12.1 
    @react-native-community/datetimepicker: 2.4.0 => 2.4.0 
    @react-native-community/netinfo: ^4.6.0 => 4.7.0 
    @reportportal/agent-js-jest: ^5.0.2 => 5.0.2 
    @testing-library/react-native: ^7.0.2 => 7.1.0 
    @types/jest: ^26.0.1 => 26.0.19 (26.0.15)
    @types/js-md5: ^0.4.2 => 0.4.2 
    @types/react: ^16.9.11 => 16.14.0 
    @types/react-native: ^0.60.1 => 0.60.31 (0.63.36)
    @types/react-native-share: ^1.1.1 => 1.1.6 
    @types/react-native-uuid-generator: ^4.0.0 => 4.0.0 
    @types/react-redux: ^7.0.1 => 7.1.11 
    @types/react-test-renderer: ^16.0.3 => 16.9.3 
    @types/redux-mock-store: ^1.0.1 => 1.0.2 
    @types/redux-thunk: ^2.1.0 => 2.1.0 
    HelloWorld:  0.0.1 
    PDFExample:  0.0.1 
    appcenter: ^4.0.2 => 4.0.2 (2.6.1)
    appcenter-analytics: ^4.0.2 => 4.0.2 (2.6.1)
    appcenter-crashes: ^4.0.2 => 4.0.2 
    aws-amplify: ^3.0.11 => 3.3.9 
    babel-jest: 26.6.3 => 26.6.3 (25.5.1)
    babel-polyfill: ^6.26.0 => 6.26.0 
    detox: ^17.6.0 => 17.13.0 
    dotenv: ^8.2.0 => 8.2.0 
    hermes-inspector-msggen:  1.0.0 
    husky: ^1.3.1 => 1.3.1 
    immer: ^8.0.1 => 8.0.1 (6.0.1)
    jest: ^26.4.2 => 26.6.3 
    jest-circus: ^26.4.2 => 26.6.3 
    jest-html-reporters: ^2.1.2 => 2.1.2 
    jest-runner-groups: ^1.0.0 => 1.1.1 
    jetifier: ^1.6.4 => 1.6.6 
    js-md5: ^0.7.3 => 0.7.3 
    metro: ^0.57.0 => 0.57.0 (0.58.0)
    metro-react-native-babel-preset: ^0.57.0 => 0.57.0 (0.58.0, 0.59.0)
    moment: ^2.24.0 => 2.29.1 
    node-fetch: ^2.6.1 => 2.6.1 (2.6.0, 1.7.3)
    on-tour-mobile-modules: file:mobile-shared-modules => 4.2.113 
    prettier: ^1.16.4 => 1.19.1 
    pretty-quick: ^1.11.1 => 1.11.1 
    react: 16.13.1 => 16.13.1 
    react-animated:  0.1.0 
    react-native: 0.63.2 => 0.63.2 
    react-native-background-fetch: ^3.1.0 => 3.1.0 
    react-native-device-info: ^5.3.1 => 5.6.5 
    react-native-gesture-handler: ^1.9.0 => 1.9.0 
    react-native-keyboard-aware-scroll-view: ^0.9.3 => 0.9.3 
    react-native-mime-types: ^2.3.0 => 2.3.0 
    react-native-notifications: ^3.3.0 => 3.4.0 
    react-native-pdf: ^5.1.0 => 5.1.7 
    react-native-reanimated: ^1.13.2 => 1.13.2 
    react-native-screens: ^2.15.0 => 2.15.0 
    react-native-share: ^1.2.1 => 1.2.1 
    react-native-splash-screen: ^3.2.0 => 3.2.0 
    react-native-testing-library: ^1.14.0 => 1.14.0 
    react-native-uuid-generator: ^6.1.1 => 6.1.1 
    react-native-webview: 7.4.1 => 7.4.1 
    react-navigation: ^4.4.3 => 4.4.3 
    react-navigation-drawer: ^1.4.0 => 1.4.0 
    react-navigation-example:  0.0.1 
    react-navigation-stack: ^1.7.3 => 1.10.3 
    react-navigation-tabs: ^1.2.0 => 1.2.0 
    react-redux: ^7.2.0 => 7.2.2 
    react-test-renderer: 16.9.0 => 16.9.0 
    redux: ^4.0.1 => 4.0.5 
    redux-example:  0.0.1 
    redux-mock-store: ^1.5.3 => 1.5.4 
    redux-persist: ^5.10.0 => 5.10.0 
    redux-persist/integration/react:  undefined ()
    redux-thunk: ^2.3.0 => 2.3.0 
    rn-fetch-blob: ^0.10.15 => 0.10.16 
    ts-jest: ^26.3.0 => 26.4.4 
    tslint: ^5.12.1 => 5.20.1 
    tslint-config-prettier: ^1.18.0 => 1.18.0 
    tslint-react: ^3.6.0 => 3.6.0 
    typesafe-actions: ^3.0.0 => 3.4.0 
    typescript: ^3.7.2 => 3.9.7 
  npmGlobalPackages:
    @aws-amplify/cli: 4.21.3
    @jghennes/snap: 1.0.0
    appcenter-cli: 2.3.0
    aws-amplify-react-native: 2.1.16
    aws-amplify: 1.1.35
    detox-cli: 10.0.7
    dotenv-cli: 3.0.0
    gql-generator: 1.0.12
    grunt: 1.0.4
    gulp: 4.0.2
    jest: 23.6.0
    npm: 6.4.1
    react-native-cli: 2.0.1
    typescript: 3.7.2
    typings: 2.1.1
    webpack-cli: 3.3.1
    webpack: 3.11.0
    yarn: 1.13.0
`
> * Are you able to repro in Simulator? Or only on physical devices?
We can reproduce in an Android emulator

> * Have you been experiencing this issue in previous versions of aws-amplify? Or only after upgrading to 3.3.27?
It appears to be in previous versions, going back to at least 3.0.11

> * Could you try using **aws-amplify@3.3.14** and letting us know if you're still running into the same issue?
The issue appears to be present in this version, as well as the most recent version

**Comment by iartemiev** [comment]
Thank you, @sconway! I'll post an update here once we've reproduced the issue

**Comment by iartemiev** [comment]
I'm able to repro this consistently. Labeling this a bug and investigating the cause.

**Comment by iartemiev** [comment]
@sconway I opened a PR with a proposed solution: https://github.com/aws-amplify/amplify-js/pull/8196
I'll provide another update after we've reviewed and merged it.

**Comment by iartemiev** [comment]
@sconway PR's been merged and is currently available in [aws-amplify@3.3.28-unstable.18](https://www.npmjs.com/package/aws-amplify/v/3.3.28-unstable.18). It'll be released as part of the next stable version later this week.

**Comment by sconway** [comment]
Awesome, thanks @iartemiev!

**Comment by iartemiev** [comment]
@sconway the bug fix has been released as part of [aws-amplify@3.4.0](https://www.npmjs.com/package/aws-amplify/v/3.4.0)

Please give it a try when you get a chance and let us know if it resolves the issue you're experiencing

**Comment by sconway** [comment]
Hi @iartemiev, this appears to be working for us. I have noticed a few rare instances where deleted items were still appearing in our application, but I have not been able to reproduce any of these cases. Going to close the issue for now, as the main issue we were seeing is now resolved. Thanks for looking into this!
