### ISSUE TITLE
DataStore Update attempting to write over its own read-only property

### ISSUE THREAD

**Issue by RobertGemmaJr** [aws-amplify/amplify-js#8649]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication, DataStore

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line
  System:
    OS: Windows 10 10.0.19043
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
    Memory: 4.42 GB / 15.75 GB
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 92.0.4515.107
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.55)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @aws-amplify/ui-react: ^1.2.6 => 1.2.6
    @material-ui/core: ^4.11.4 => 4.11.4
    @material-ui/data-grid: ^4.0.0-alpha.32 => 4.0.0-alpha.32
    @material-ui/icons: ^4.11.2 => 4.11.2
    aws-amplify: ^4.2.0 => 4.2.0
    cross-env: ^7.0.3 => 7.0.3
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    react-scripts: 4.0.3 => 4.0.3
    web-vitals: ^1.1.2 => 1.1.2
  npmGlobalPackages:
    @aws-amplify/cli: 5.1.2
    nodemon: 2.0.4
    npm: 6.14.9
    rimraf: 3.0.2


```

</details>

### Describe the bug

Error: createdAt is read-only
DataStore.save is attempting to update a read-only property (createdAt) of my Setting model.

I am able to call Setting.copyOf fine on its own, the error is occurring in DataStore.save. At no point do I interact with createdAt for any Setting models, I'm not sure what's going on under the hood.

### Expected behavior

Setting model is updated locally
Model is synced with cloud

### Reproduction steps

1. User updates settings on a <Menu> page. Everything is controlled using React.useState
2.  User clicks a "Save" button, triggering the DataStore event

### Code Snippet

Function Call:
```javascript
async function handleSaveClick() {
    // Note: May not have to set hooks since I reload the website

    const newSettings = {
      title: state.newTitle,
      randomizeQuestions: state.newRandomizeQuestions,
      recordTemperature: state.newRecordTemperature,
      keepTemperature: state.newKeepTemperature,
      tempTolerance: state.newTempTolerance,
    }
    const res = await updateSettings(newSettings);
    setSettings(settings) // TEMP - update response
    console.log(res)
```
The DataStore event:
```javascript
export async function updateSettings(newSettings) {
  const original = await getSettings();
  console.log("Original", original);

  // This is throwing an error.
  // createdAt has changed but Amplify is trying to update it
  await DataStore.save(Setting.copyOf(original, updated => {
    updated.title = newSettings.title;
    updated.randomizeQuestions = newSettings.randomizeQuestions;
    updated.recordTemperature = newSettings.recordTemperature;
    updated.keepTemperature = newSettings.keepTemperature;
    updated.tempTolerance = newSettings.tempTolerance;
  }));

  const after = await DataStore.query(Setting);
  console.log("Check difference", original, after)
  return "done" // TEMP
}

```

Schema:
```javascript
type Setting @model @auth(rules: [{allow: owner}]) {
  id: ID!
  title: String!
  randomizeQuestions: Boolean!
  recordTemperature: Boolean!
  keepTemperature: Boolean!
  tempTolerance: Float!
}
```

### Log output

<details>

```
// Put your logs below this line
api.js:97 Original Model {id: "c766e8e7-087f-4582-a5ba-d299ae935ee1", title: "Change Title in Menu", randomizeQuestions: true, recordTemperature: true, keepTemperature: true, …}
datastore.ts:854 Uncaught (in promise) Error: createdAt is read-only.
    at datastore.ts:854
    at Array.forEach (<anonymous>)
    at DataStore.checkReadOnlyProperty (datastore.ts:852)
    at DataStore.<anonymous> (datastore.ts:818)
    at step (multiAuthStrategy.ts:121)
    at Object.next (multiAuthStrategy.ts:121)
    at fulfilled (multiAuthStrategy.ts:121)
(anonymous) @ datastore.ts:854
DataStore.checkReadOnlyProperty @ datastore.ts:852
(anonymous) @ datastore.ts:818
step @ multiAuthStrategy.ts:121
(anonymous) @ multiAuthStrategy.ts:121
fulfilled @ multiAuthStrategy.ts:121
async function (async)
handleSaveClick @ Menu.jsx:90
onClick @ Menu.jsx:161
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4070
executeDispatch @ react-dom.development.js:8243
processDispatchQueueItemsInOrder @ react-dom.development.js:8275
processDispatchQueue @ react-dom.development.js:8288
dispatchEventsForPlugins @ react-dom.development.js:8299
(anonymous) @ react-dom.development.js:8508
batchedEventUpdates$1 @ react-dom.development.js:22396
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889

```

</details>
[DataStore error.log](https://github.com/aws-amplify/amplify-js/files/6888100/DataStore.error.log)

### aws-exports.js

```javascript
const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:*****-*****-*****-*****-**********",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_*****",
    "aws_user_pools_web_client_id": "********************",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://***************.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-********************"
};


export default awsmobile;
```

Edit by @iartemiev  - redacted config info

**Comment by nickarocho** [comment]
Hi @RobertGemmaJr, thank you for raising this concern with us, and thank you for the thorough explanation and providing code snippets - this makes it so much easier for us to investigate and is much appreciated.

I am going to try and reproduce the issue on my end using a similar set up as to that of your app/schema.

Thank you for your patience while I look into this. If anything else comes to mind which might provide a clue please don't hesitate to drop another comment. Otherwise, I will update you as soon as I have something to report!

**Comment by RobertGemmaJr** [comment]
Thank you! One thing that I suppose is worth noting is that I only ever have one Setting object in my program (technically one per user with amplify auth). I don't see how it would change anything but that's the use of this model in my program.

Another thing to note is that a different schema of mine overrides the createdAt member. Again, I have no idea if this would make a difference (it's used in an entirely different part of code) but is worth noting. Looking back at it I don't really need to do this override anymore. I can look to make that change and see if that fixes anything.

```graphql
type Submission @model @auth(rules: [{allow: owner}]) @key(name: "byPerson", fields: ["personID"]) {
  id: ID!
  personID: ID!
  createdAt: AWSDateTime!
  formType: PTYPE!
  time: TIME!
  questions: [ID!]!
  responses: [String!]!
  temperature: String
  passed: Boolean!
}
```

**Comment by nickarocho** [comment]
@RobertGemmaJr thank you for the additional information. Since we recently exposed the `createdAt` and `updatedAt` fields as `readonly` fields which you can now access within the application, I would definitely recommend removing the `createdAt` field and doing a fresh `amplify codegen models` to generate the proper Graph QL code and subsequently a fresh `amplify push` once that is done to push your changes up to the cloud.

I would be very interested to know if this somehow solves your problem (it is possible your schema has inter-dependencies on separate models and somehow this field is being updated behind the scenes).

It does seem odd to me that you would get this error without _explicitly_ trying to overwrite the `createdAt` field, so I would suspect this actually might have something to do with it.

In the meantime I will keep attempting to reproduce on my end. Is the code for your app open source? It would be much easier for me to fork your repo and mess with it locally than stabbing in the dark with a Frankenstein app which is attempting to mimic your app's functionality.

**Comment by nickarocho** [comment]
Also, could you please share the `getSettings` method?

**Comment by RobertGemmaJr** [comment]
Unfortunately I'm developing for a client so no, it is not open source. I will definitely make that schema change and see if that fixes things. Hopefully I'll have good new soon!

I have included ```getSettings``` below. I fixed the bug that was unnecessarily creating additional models (I wasn't waiting for DataStore to finish syncing) but I've left the error message for now.

```javascript
// Returns all models of type Setting
// There should be exactly 1 per user
export async function getSettings() {
  var models = await DataStore.query(Setting);

  // TODO: Move this to the auth sign-up listener
  if (!models.length) {
    await DataStore.save(
      new Setting({
        "title": "Change Title in Menu",
        "randomizeQuestions": true,
        "recordTemperature": true,
        "keepTemperature": true,
        "tempTolerance": 2,
      })
    );
    models = await DataStore.query(Setting)    
  } else if (models.length > 1) {
    console.error("Too many settings! Using first object", models)
  }
  return models[0];
}
````

**Comment by RobertGemmaJr** [comment]
Update:

The DataStore issue appears to have healed itself. Perhaps ending the local host (last night) and restarting it (this morning) cleared some sort of cache that solved the issue? 

I did go ahead and remove the ```createdAt``` field from my ```Submission``` model as well. However, the ```createdAt``` field is not being created again by Amplify. Neither the ```createdAt``` nor ```updatedAt``` fields are present for this model. Is there some way to force amplify to regenerate these fields? I've tried ```amplify codegen models```, ```amplify push```, etc. - nothing seems to work.

**Comment by nickarocho** [comment]
Glad to hear that solved it!

Can you check your `cli.json` config file and verify you have the `addtimestampfields` flag set to `true`? This is the feature flag we added to account for backwards compatibility for `readonly` properties to be exposed in the models.

**Comment by RobertGemmaJr** [comment]
Yes, ```addtimestampfields``` is ```true```.  I can read the properties on my other models, it is only the model that I overwrote (and now undone) that the properties aren't present. I've gone as far as deleting all of the data in the model's DynamoDB and doing a fresh pull/push but I can't get Amplify to regenerate the properties.

**Comment by guioum** [comment]
I fixed this issue for myself by switching addtimestampfields to false, then amplify codegen models, then switching back addtimestampfields to true, then amplify codegen models.

**Comment by nickarocho** [comment]
@guioum this is interesting, thank you for helping us look into this.

@RobertGemmaJr can you try this? (set `addtimestampfields` to false, run `amplify codegen models`, then set back to `true` and run the same to verify as a second source)

I am looking into the library to see what is going on but hopefully this will unblock you for the meantime.

**Comment by RobertGemmaJr** [comment]
I tried to no avail. I am no longer getting the original read-only error at all but still cannot get my ```Submission``` model to show ```createdAt``` and the other Amplify timestamp fields. A couple things to note:

1.  All other models contain all the correct fields (included ```Settings``` below)
2. ```owner```, ```createdAt```, and ```updatedAt``` ARE in schema.js
3. ```owner```, ```createdAt```, and ```updatedAt``` ARE in DynamoDB
4. ```owner```, ```createdAt```, and ```updatedAt``` ARE NOT in my react app

Below are the ```console.logs()``` of the objects

```Setting``` : All correct
```javascript
Model {...}
createdAt: "2021-07-21T17:51:52.743Z"
id: "c766e8e7-087f-4582-a5ba-d299ae935ee1"
keepTemperature: false
owner: "demouser"
randomizeQuestions: false
recordTemperature: true
tempTolerance: 2
title: "Apple Blossom"
updatedAt: "2021-08-04T00:33:35.948Z"
_deleted: null
_lastChangedAt: 1628037234956
_version: 28
[[Prototype]]: Object
```

```Submission``` : Missing Amplify fields
```javascript
Model {...}
formType: "STAFF"
id: "ad02d2f8-66f4-4b86-b9b8-8592288833c4"
passed: false
personID: "beebc088-dfce-48e5-98c4-ae9a8412731d"
questions: (12) ["8abeb3c7-3806-4d1b-84ae-2f8acbffd233", "8ef52569-53f8-422b-9c3c-0efcfac81e63", "10859c89-4d8c-418f-a666-509e6b896baf", "730f4006-ff17-4ea2-99ec-48d9fceb4de8", "b07b9738-6283-4e5a-a3ca-e69dc2de1d47", "28f610f4-caa9-45b2-a010-9d64eb6c2a67", "5cfcb0b7-b5f6-46a4-b6ad-10312dc9b350", "0078eb00-4c16-42d1-b60e-569e36dd18ac", "9254ec42-8dc6-40bd-89ed-151a2ec765fd", "96513d35-53ca-4739-a8d2-f2cd422e5d83", "2255c98d-de4c-4507-b05b-60521b217c92", "726d6e3e-e529-45d9-b90b-9e38447103b1"]
responses: (12) ["No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No"]
temperature: "Passed"
time: "MORNING"
_deleted: undefined
_lastChangedAt: undefined
_version: undefined
[[Prototype]]: Object
```

I find it very telling that the ```owner``` field is not available in the ```Submission``` object. The fields are being created - they show up in DynamoDB. So it has to be something with Amplify, no? I've even added a DataStore.clear() in my initialization process. Nothing seems to be working.

**Comment by RobertGemmaJr** [comment]
Something else to note - ```Submission``` is my only Model with a key property. From the schema:

```graphql
type Submission @model 
                @auth(rules: [{allow: owner}])
                @key(name: "byPerson", fields: ["personID"]) {
  id: ID!
  personID: ID!
  formType: PTYPE!
  time: TIME!
  questions: [ID!]!
  responses: [String!]!
  temperature: String
  passed: Boolean!
}
```

**Comment by andreasanta** [comment]
I solved this by executing

```delete queriedModel['createdAt']```

Before passing it to `copyOf`

**Comment by nickarocho** [comment]
Hi @RobertGemmaJr, I'm still having trouble reproducing the problem on my end. Could you please provide me with the contents of your `index.d.ts` file within `src/models`. There should be a `type SubmissionMetaData` in there with `readOnlyFields`. This gets generated via `amplify codegen models` with the `addtimestamps` flag set to `true`. 

I would anticipate that type being present in `index.d.ts`, but I'm just curious if the contents of that file might lead us to more clues.

**Comment by nickarocho** [comment]
@RobertGemmaJr I have gone back and forth with the `addtimestampfields` set to `true` and `false` (and running `amplify codegen models` in between), and have successfully verified that the `createdAt` and `updatedAt` fields appear when expected, and don't appear when expected NOT to appear. I have `@key` directives on one of my models as well so I don't think that has anything to do with it.

I feel like there must be some extra code somewhere doing something funky. You mentioned previously:
> Another thing to note is that a different schema of mine overrides the createdAt member. Again, I have no idea if this would make a difference (it's used in an entirely different part of code) but is worth noting.

Do you still have this "different schema" in place? I'm wondering what this different schema is, why it is necessary, and what differences it might have to the primary schema.

**Comment by andreasanta** [comment]
@nickarocho Apologies if I couldn't post any code, but I can reproduce it by: 

* Leaving the default config on, so `addtimestampfields:true`
* Querying for a model that exists and thus has already set the fields updatedAt and createdAt
* Executing a Model.copyOf the queried model
* Altering some fields inside the callback of the copyOf function
* Attempting to save the result

I get an error notifying me that the property createdAt is read-only.

**Comment by nickarocho** [comment]
@andreasanta what version of Amplify are you using?

**Comment by andreasanta** [comment]
@nickarocho  `"aws-amplify": "^4.2.2"`

**Comment by RobertGemmaJr** [comment]
@nickarocho My ```Submission``` model is the one that _used_ to override the ```createdAt``` member. I have since removed that override.

My issue is that now I can't get amplify to re-generate its "internal" timestampfields. The ```owner``` field  is also not present in my program. 

To be clear I am no longer dealing with the ```createdAt is readonly``` error. I am merely trying to get amplify to generate the properties. They are definitely being created - I even get VS Code intellisense for the members. They're available everywhere except for in the browser.

**Comment by nickarocho** [comment]
@RobertGemmaJr thanks for the clarification.

I also wasn't seeing the `createdAt` or `updatedAt` in one of my sample DataStore React apps. After adding Auth to my project and adding the `@auth(rules: [{ allow: owner }])` directive to one of my models, running `amplify push`, and finally re-running `amplify codegen models`, the timestamp fields appeared in the browser for me.

Is the `owner` field getting added to other models but not the `Submission` model?

**Comment by RobertGemmaJr** [comment]
The ```owner``` field is added to all of my models. I tried cycling it by removing ```@auth(rules: [{ allow: owner }])````, pushing, adding it back, and pushing again but no luck.

**Comment by RobertGemmaJr** [comment]
Here's my index.d.ts file:

```typescript
import { ModelInit, MutableModel, PersistentModelConstructor } from "@aws-amplify/datastore";

export enum Qtype {
  BOOLEAN = "BOOLEAN",
  TEXT = "TEXT"
}

export enum Ptype {
  FAMILY = "FAMILY",
  STAFF = "STAFF",
  MANUAL = "MANUAL"
}

export enum Time {
  MORNING = "MORNING",
  AFTERNOON = "AFTERNOON"
}

export enum Content {
  HOME = "HOME",
  MENU = "MENU",
  MANUAL = "MANUAL",
  KEYPAD = "KEYPAD",
  PEOPLE = "PEOPLE",
  QUESTIONNAIRE = "QUESTIONNAIRE",
  SUMMARY = "SUMMARY"
}



type SettingMetaData = {
  readOnlyFields: 'createdAt' | 'updatedAt';
}

type PersonMetaData = {
  readOnlyFields: 'createdAt' | 'updatedAt';
}

type SubmissionMetaData = {
  readOnlyFields: 'createdAt' | 'updatedAt';
}

type QuestionMetaData = {
  readOnlyFields: 'createdAt' | 'updatedAt';
}

export declare class Setting {
  readonly id: string;
  readonly title: string;
  readonly randomizeQuestions: boolean;
  readonly recordTemperature: boolean;
  readonly keepTemperature: boolean;
  readonly tempTolerance: number;
  readonly createdAt?: string;
  readonly updatedAt?: string;
  constructor(init: ModelInit<Setting, SettingMetaData>);
  static copyOf(source: Setting, mutator: (draft: MutableModel<Setting, SettingMetaData>) => MutableModel<Setting, SettingMetaData> | void): Setting;
}

export declare class Person {
  readonly id: string;
  readonly companyID?: number;
  readonly type: Ptype | keyof typeof Ptype;
  readonly fName: string;
  readonly lName: string;
  readonly Submissions: (Submission | null)[];
  readonly createdAt?: string;
  readonly updatedAt?: string;
  constructor(init: ModelInit<Person, PersonMetaData>);
  static copyOf(source: Person, mutator: (draft: MutableModel<Person, PersonMetaData>) => MutableModel<Person, PersonMetaData> | void): Person;
}

export declare class Submission {
  readonly id: string;
  readonly personID: string;
  readonly formType: Ptype | keyof typeof Ptype;
  readonly time: Time | keyof typeof Time;
  readonly questions: string[];
  readonly responses: string[];
  readonly temperature?: string;
  readonly passed: boolean;
  readonly createdAt?: string;
  readonly updatedAt?: string;
  constructor(init: ModelInit<Submission, SubmissionMetaData>);
  static copyOf(source: Submission, mutator: (draft: MutableModel<Submission, SubmissionMetaData>) => MutableModel<Submission, SubmissionMetaData> | void): Submission;
}

export declare class Question {
  readonly id: string;
  readonly index: number;
  readonly type: Qtype | keyof typeof Qtype;
  readonly question: string;
  readonly expectedResponse: string;
  readonly checkboxes: boolean[];
  readonly createdAt?: string;
  readonly updatedAt?: string;
  constructor(init: ModelInit<Question, QuestionMetaData>);
  static copyOf(source: Question, mutator: (draft: MutableModel<Question, QuestionMetaData>) => MutableModel<Question, QuestionMetaData> | void): Question;
}
```

**Comment by nickarocho** [comment]
> The `owner` field is added to all of my models. I tried cycling it by removing ```@auth(rules: [{ allow: owner }])````, pushing, adding it back, and pushing again but no luck.

@RobertGemmaJr just to clarify, you also ran `amplify codegen models` at the end of this process right?

**Comment by RobertGemmaJr** [comment]
Yes, I ran it before and after each push

**Comment by nickarocho** [comment]
@RobertGemmaJr thanks for your patience while we work through this together - I am going to create a fresh app today with your exact schema to see if I can force a way to reproduce the problem.

At this point it is really tough to point to where your issue might be stemming from without seeing the full codebase or a sample repo I could fork where the problem definitely exists.

I'll let you know what I find after creating the new app with your schema.

**Comment by andreasanta** [comment]
This is fixed for me in 4.2.6 :)

**Comment by iartemiev** [comment]
Thanks for pointing that out, @andreasanta! It's indeed fixed in the latest release of Amplify. I'm going to close this issue but if anyone is still experiencing this error after upgrading, please comment and we can re-open.
